### ISSUE TITLE
ffprobe -show_entries before -show_frames

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#102]
Hi @kokorin,

I hope you are well.

I've noticed FFprobe adds `-show_entries [expr]` before e.g. ` -show_frames` which does not produce the expected filtering. Instead every property of the frame is returned (BTW, I'm using FFmpeg 4.3.1). I think this might be a bug and `-show_entries` should be added last. What are your thoughts?

Have a good evening.

Cheers,
-Jon

**Comment by kokorin** [comment]
Hi @jonfryd ,

Honestly I think that `-show_entries` and `--show_format` should be removed from Jaffree's `FFprobe` wrapper. Since you have to write code anyway to use `FFprobeResult` there should be no problem with extra parsed values.

Best Regards,
Denis

**Comment by jonfryd** [comment]
What I'm doing as a workaround right now is adding "-show_entries [expr]" as arguments (via `addArguments()`). This ensures it's added after `-show_format` in the generated command. This is fine for now.

**Comment by jonfryd** [comment]
BTW, why do want to remove `-show_entries` and `-show_format`?

**Comment by kokorin** [comment]
Because these properties only minimize ffprobe output and don't actually
affect Java code.
Can you describe when you need those flags?

вт, 15 дек. 2020 г., 19:12 Jon Frydensbjerg <notifications@github.com>:

**Comment by jonfryd** [comment]
I'm using ffprobe to find PTS timestamps of video keyframes.

For example:

```
        final FFprobeResult ffProbeResult = FFprobe.atPath(_ffmpegPathBin)
                .setInput(_probePath)
                .setReadIntervals("0%+40")
                .setSelectStreams(StreamSpecifier.withType(StreamType.VIDEO))
                .setShowFrames(true)
                .setShowPrivateData(false)
                .addArguments("-skip_frame", "nokey")
                .addArguments("-show_entries", "frame=pkt_pts_time")
                .execute();
```

Reducing  ffprobe's output (via `-show_entries`) here makes sense to me since we are potentially returning hundreds of frames.

**Comment by kokorin** [comment]
@jonfryd I have check the issue, It appeared that `-show_entries` does not require any other **show** options (`show_format`, etc).
So `-show_entries "packet=pts_time,duration_time,stream_index : stream=index,codec_type"` will cause packet and stream data to be printed by ffprobe.

**Comment by jonfryd** [comment]
So do you mean "-show_frames" is redundant and can be left out?

The output of the following commands are not identical on the video file I'm testing on:

1. `ffprobe -show_entries "frame=pkt_pts_time" [video]`

```
...
[FRAME]
pkt_pts_time=19.960000
[SIDE_DATA]
[/SIDE_DATA]
[SIDE_DATA]
[/SIDE_DATA]
[SIDE_DATA]
[/SIDE_DATA]
[SIDE_DATA]
[/SIDE_DATA]
[/FRAME]
[FRAME]
pkt_pts_time=19.960000
[/FRAME]
```

2. `ffprobe -show_frames -show_entries "frame=pkt_pts_time" [video]`

```
...
[FRAME]
pkt_pts_time=19.960000
[SIDE_DATA]
side_data_type=AVPanScan
[/SIDE_DATA]
[SIDE_DATA]
side_data_type=QP table data
[/SIDE_DATA]
[SIDE_DATA]
side_data_type=QP table properties
[/SIDE_DATA]
[SIDE_DATA]
side_data_type=GOP timecode
timecode=00:01:19:24
[/SIDE_DATA]
[/FRAME]
[FRAME]
pkt_pts_time=19.960000
[/FRAME]
```

Notice that side data including the GOP timecode is not included in the latter.

**Comment by kokorin** [comment]
@jonfryd I have no exact answer why output is different in this two cases, but it's clear that ffmpeg developers created `-show_frames` and `-show_entries` to be mutually exclusive.

To show side data type you have to specify side_data section with `-show_entries`:
```
ffprobe  -show_entries frame=width:side_data=side_data_type  -i .artifacts/160x120_1fps_20s.mjpeg
...
[FRAME]
width=160
[SIDE_DATA]
side_data_type=QP table data
[/SIDE_DATA]
[SIDE_DATA]
side_data_type=QP table properties
[/SIDE_DATA]
[/FRAME]
[STREAM]
[/STREAM]
```

**Comment by jonfryd** [comment]
Cool, thanks, @kokorin! I've confirmed this works.

I'll fix it on our side then. Closing this one.
