### ISSUE TITLE
How to log what FFMpeg outputs to standard error?

### ISSUE THREAD

**Issue by pszemus** [kokorin/Jaffree#104]
FFmpeg outputs it's log messages to standard error. Is `FFmpeg.setOutputListener` the only option to log those messages?

**Comment by kokorin** [comment]
Seems it is so currently. 

Actually now I'm not sure where ffmpeg sends log messages: to stderr or stdout. Probably it's stderr, because stdout is used to send output to Linux pipe.

I created similar issue #87 some time ago.

**Comment by pszemus** [comment]
You are correct. FFmpeg sends it's log messages to stderr. 
I've finished with:
```
FFmpeg
	.setOutputListener((line) -> {
		log.info(line);
		return true;
	})
	.setContextName(threadNameForLogging)
```

**Comment by kokorin** [comment]
Actually `FFmpegResultReader` already dumps all ffmpeg output with debug level.

So probably `FFmpegResultReader`  should contain some logic to parse ffmpeg log messages and re-log them using SLF4J.

**Comment by pszemus** [comment]
ffmpeg's `-loglevel` option can have `flags+` value set to `level`:
```
‘level’
Indicates that log output should add a [level] prefix to each message line. This can be used as an alternative to log coloring, e.g. when dumping the log to file.
```
http://ffmpeg.org/ffmpeg.html#toc-Generic-options

Maybe that could be parsed and lines with level < relevant slf4j's level would be displayed?

**Comment by kokorin** [comment]
Sure, but no need to detect what can be shown by SLF4j. It's required just
to redirect ffmpeg's debug to SLF4J debug, trace -> trace, warn -> warn,
etc.

**Comment by pszemus** [comment]
Ouch... I wanted to have FFmpeg's output but without flooding my logs with runtime stats so I turned them off with `-nostats` but now I don't have `ProgressListener.onProgress` callbacks... I guess what I'm trying to do here is to _have my cake and eat it_.
What I'm left with is filtering out those stat lines in `OutputListener.onOutput` before logging.

**Comment by kokorin** [comment]
You can configure different log Appenders in log4j2 for example. You can
store to a file ffmpeg output while sending to console app logs.

**Comment by kokorin** [comment]
Also it would be great if you can provide while ffmpeg commands you execute
and ffmpeg console output

**Comment by pszemus** [comment]
I tried to log all FFmpeg output by setting DEBUG log level for `com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader` and it worked but then my logs were flooded by FFmpeg runtime stats:
```
frame=  162 fps= 28 q=-1.0 Lsize=N/A time=00:00:05.78 bitrate=N/A speed=0.993x
[...]
```
When I turned them off by `-nostats` I lost `ProgressListener.onProgress` callbacks.
That's what I meant by _to have my cake and eat it_.

If I stick to:
```
.setOutputListener((line) -> {
	log.info(line);
	return true;
})
```
those FFmpeg runtime stats are consumed by `ProgressListener` and `OutputListener` has only the lines I need.

**Comment by kokorin** [comment]
Maybe it makes sense to add a dedicated LogListener. Will think about it.

**Comment by kokorin** [comment]
Hello @pszemus I have create PR #115, It parses ffmpeg progress sent to local TCP socket. Also it detects ffmpeg output loglevel for every line and logs it with corresponding SLF4J log level.

**Comment by kokorin** [comment]
0.9.10 version released, should be available in Maven Central
