### ISSUE TITLE
Feature request: Async FFprobe execution

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#106]
Hi @kokorin,

For certain files and formats ffprobe can take a very long time to execute (e.g. when a .mxf file is stored on a remote server and accessed via HTTPS). Any chance we can have async FFprobe execution at some point similar to what you have already done in the FFmpeg class?

Have a nice weekend.

Best regards,
-Jon

**Comment by kokorin** [comment]
Hi Jon. Will take a look.

**Comment by jonfryd** [comment]
Thanks!

**Comment by kokorin** [comment]
Release 0.9.8 will be available in Maven central in several hours

**Comment by jonfryd** [comment]
Excellent - much appreciated, @kokorin!
