### ISSUE TITLE
FrameOutput leaks ServerSockets and Threads if the ffmpeg-call never produces any output.

### ISSUE THREAD

**Issue by mamyreen** [kokorin/Jaffree#108]
If ffmpeg never produces any output it will never connect to the TCP ServerSocket.
This causes the HelperThread createdby SocketOutput to block in ServerSocket.accept().
Interrupting the thread at this point has no effect. 

The ServerSocket should always be closed when the ffmpeg process is stopped/exited.

A case where this might happen is if the input is a RTP-stream and no video/packets is received by ffmpeg. Then the process will exit after 10 seconds because of lack of input/output. In this scenario the FrameOutput will never exit the Thread which is stuck in ServerSocket.accept and the ServerSocket will never be closed.

**Comment by kokorin** [comment]
@mamyreen interesting that you mentioned this. I have addressed `ServerSocket` close issue in COMMON_TCP branch.

It would be great if you provide a test showing the problem.

**Comment by kokorin** [comment]
@mamyreen the fix is in develop branch. I introduced `FFHelper` interface (instead of Runnable). `ProcessHandler` closes all passed in `FFHelper`s when execution is completed. Also `TcpServer` overrides `finalize()` method to ensure `ServerSocket` will be closed sooner or later.

**Comment by kokorin** [comment]
Fixed. Release 0.9.8 will be available in Maven central in several hours

**Comment by mamyreen** [comment]
I can confirm that the 0.9.8 release fixes this issue.

**Comment by kokorin** [comment]
Great! Thanks for your feedback.
