### ISSUE TITLE
playing 64 video streams

### ISSUE THREAD

**Issue by sjaiswal25** [kokorin/Jaffree#11]
I am trying to play 64 video feeds simultaneously, but the performance degrades as the number of streams played increases. Is there an optimization method for the same?

**Comment by kokorin** [comment]
What command do you use for playing? Do you run 64 ffmpeg instances simultaneously?

Anyway the best you cant get if performance degrades in directly proportional manner.

**Comment by kokorin** [comment]
No reply, closing
