### ISSUE TITLE
NutInputStream never checks for EOS return value for InputStream.read()

### ISSUE THREAD

**Issue by mamyreen** [kokorin/Jaffree#111]
If the ffmpeg execution fails to start sending data or the data is cut short the NutInputStream can cause OutOfMemoryErrors.

Tested by opening a video-file and piping two of the outputs, one as a FrameOuput and the other as a PipeOuput mapped to an expected data stream in the video.

If the data stream is missing from the video file, then ffmpeg exits. But the NutInputStream does not check that the wrapped InputStream is abruptly closed. This may cause an infinte loop with a growing array allocation.

Stacktrace:
[jaffree-OutOfMemoryError.txt](https://github.com/kokorin/Jaffree/files/5866284/jaffree-OutOfMemoryError.txt)

Outputs:
[outputs.txt](https://github.com/kokorin/Jaffree/files/5866288/outputs.txt)

**Comment by kokorin** [comment]
Fixed in 0.9.9 version. It will be available on Maven central in several hours.
I would like to thank you for pointing out to the problem. It revealed critical bug NutInputStream seek, which was introduced in 0.9.8
