### ISSUE TITLE
Passing additional input flags

### ISSUE THREAD

**Issue by EmilyBjoerk** [kokorin/Jaffree#120]
I may be mistaken, but it seems impossible to generate an FFMPEG command like so:

```
 ffmpeg -i some.png  -ss 295 -i some.mkv -an -filter_complex  "blend=difference:shortest=1,blackframe=99:32" -f null -
```

Is this indeed not possible? I tried the following:

```
		FFmpeg ffmpeg = FFmpeg.atPath(Path.of(settings.getString(Settings.FFMPEG_DIR)))
				.addInput(aTriggerScreen)
				.addArguments("-ss", Double.toString(aTime))
				.addInput(aVideoPath)
				.addArgument("-an")
				.addArguments("-filter_complex", "blend=difference:shortest=1,blackframe=99:32");
```

but the -ss and -an flags are appended at the back instead of their correct positions.

**Comment by kokorin** [comment]
Input arguments should be added to input, not to FFmpeg, because different
inputs may have different arguments.
Such example is missing in readme, I will update it.

пт, 12 февр. 2021 г., 01:21 Emily <notifications@github.com>:

**Comment by kokorin** [comment]
Check methods available in UrlInput class

пт, 12 февр. 2021 г., 06:19 Denis Kokorin <kokorin86@gmail.com>:

**Comment by kokorin** [comment]
Here is an example
```
FFmpeg.atPath()
    .addInput(
            UrlInput.fromUrl(pathToSrc)
                    .setPosition(10, TimeUnit.SECONDS)
                    .setDuration(42, TimeUnit.SECONDS)
    )
    .addOutput(
            UrlOutput.toUrl(pathToDst)
                    .setPosition(10, TimeUnit.SECONDS)
    )
    .setFilter(StreamType.VIDEO, "scale=160:-2")
    .setOverwriteOutput(true)
    .execute();
```

**Comment by kokorin** [comment]
Readme updated
