### ISSUE TITLE
Mapping FFMpeg's potential errors to Exceptions

### ISSUE THREAD

**Issue by Dan-Mikkel** [kokorin/Jaffree#123]
Continuing on the topic of Exceptions: 
I think it would be a good idea to map the different errors that FFmpeg gives us to different Exceptions, in order to make it easier for consumers to handle errors that might happen in the app.
I came across this which can be a handy reference:
https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/error.c

**Comment by kokorin** [comment]
Not sure. Would you catch `InvalidArgumentFFException` to understand input arguments are not correct? Or `TooManyOpenFilesFFException`?

**Comment by Dan-Mikkel** [comment]
Good morning.

Yeah, something like that. When i use Jaffree, it would be a lot of help if i could know if the mistake was because of something i wrote or something my users did. I use Jaffree in a Spring Boot application where users can use the awesomeness of FFmpeg through the API, so that instead of having an exceptionHandler that has to manually traverse and parse the exception messages, it would be better if i could catch and handle different exceptions as they happened and then throw something a bit more useful for my domain back to the end-user.

**Comment by kokorin** [comment]
Hello @Dan-Mikkel 

I see your point, but that would meant that such messages are mapped to exception types in Jaffree.
The project currently contains 113 classes in src/main and I fill it's not a good idea to add 70+ exceptions.

**Comment by kokorin** [comment]
P.S. I hope in your project you don't encode media files while serving HTTP request

**Comment by Dan-Mikkel** [comment]
> Hello @Dan-Mikkel
> 
> I see your point, but that would meant that such messages are mapped to exception types in Jaffree.
> The project currently contains 113 classes in src/main and I fill it's not a good idea to add 70+ exceptions.

That's also a good point, maybe the custom Exception i added is the only thing that's needed for future needs?
I am willing to wait and try it out.

**Comment by Dan-Mikkel** [comment]
> P.S. I hope in your project you don't encode media files while serving HTTP request

What's the worst that could happen? Anything i should do to make it more robust?
