### ISSUE TITLE
Split video and save it

### ISSUE THREAD

**Issue by MohamedHassanKhames** [kokorin/Jaffree#126]
Is it possible to use your project to cut parts of the video and then use it? 
For example, I have a 30 seconds video and I want to split it into 3 videos and push them into kafka.
Is it possible?

**Comment by kokorin** [comment]
Yes. I hope you are not going to push video content as a message to Kafka.

**Comment by MohamedHassanKhames** [comment]
Unfortunately, I'll use kafka. However, could you show me any example for saving the video?

**Comment by MohamedHassanKhames** [comment]
To save your time, is there a way to get the result as a byte array?

**Comment by kokorin** [comment]
Check PipeOutput

вт, 23 февр. 2021 г., 11:50 MohamedHassanKhames <notifications@github.com>:

**Comment by MohamedHassanKhames** [comment]
You're writing into an outputstream so I'll not be able to get the data.

**Comment by kokorin** [comment]
ByteArrayOutputStream?

вт, 23 февр. 2021 г., 13:25 MohamedHassanKhames <notifications@github.com>:

**Comment by MohamedHassanKhames** [comment]
Do I have to set the format here: "PipeOutput.pumpTo(outputStream).setFormat("flv") " 
And if so what are the other formats types? 
Thanks.

**Comment by kokorin** [comment]
Jaffree is just an ffmpeg CLI wrapper. I would recommend first experimenting with ffmpeg to understand if its output fits your needs.

Regarding your question: one can't simple encode video into OutputStream. Only a few video formats (i.e. containers) suport streaming encoding (i.e. without backward seeking). FLV is one of streaming formats. If you need mp4 you have 2 options: encode into a file, encode into bytearray (of corresponding size) wrapped with SeekableByteChannel via ChannelOutput.
