### ISSUE TITLE
concatenate result videos  

### ISSUE THREAD

**Issue by MohamedHassanKhames** [kokorin/Jaffree#128]
I tried to concatenate two videos after using this example https://github.com/kokorin/Jaffree/blob/master/src/test/java/examples/CutAndScaleExample.java
without scaling or encoding. However, after that, I tried to merge two videos together but it didn't work. 
Do you have any idea why? 

For the concatenation, I used this command: 
ffmpeg -i "concat:vid_1.mp4|vid_2.mp4" -c copy out.mp4

**Comment by kokorin** [comment]
Try without `-c copy`. You can also check [ffmpeg concat documentation](https://trac.ffmpeg.org/wiki/Concatenate).

It's better to ask ffmpeg-related questions on stackoverflow or ffmpeg forum (or mailing list). 
Closing as not-related directly to Jaffree.
