### ISSUE TITLE
Bug in OutputListener behavior since version 0.9.10

### ISSUE THREAD

**Issue by skythor17** [kokorin/Jaffree#129]
Hi there,

first of all a big thank you for developing this wonderful tool.

I'm encountering a bug when using an OutputListener for custom parsing of ffmpeg output. It still works fine with this version from Maven:

		<dependency>
			<groupId>com.github.kokorin.jaffree</groupId>
			<artifactId>jaffree</artifactId>
			<version>0.9.9</version>
		</dependency>

My code looks as follows:

```
  public boolean isInterlaced(File mediaFile)
      throws AmbiguousInterlacedStateException, UnknownInterlacedStateException {
    Path inputPath = Paths.get(mediaFile.getAbsolutePath());

    FFmpeg ffmpeg = FFInitializer.newFFMpeg();

    if (skipSeconds > 0) {
      ffmpeg.addArguments("-ss", Integer.toString(skipSeconds));
    }

    ffmpeg.addInput(UrlInput.fromPath(inputPath));
    ffmpeg.setFilter("idet");
    ffmpeg.addArguments("-frames:v", Integer.toString(frames));
    ffmpeg.addArguments("-map", "0:v:0");
    ffmpeg.addArguments("-c:v", "rawvideo");
    ffmpeg.setOverwriteOutput(true);
    ffmpeg.addOutput(new NullOutput(false));

    final FrameDetections frameDetections = new FrameDetections();
    ffmpeg.setOutputListener(line -> {
      System.out.println(line); // FIXME debug
      frameDetections.setSingleIgnoreNull(match(singlePattern, line));
      frameDetections.setMultiIgnoreNull(match(multiPattern, line));
      return true;
    });

    try {
      ffmpeg.execute();
    } catch (RuntimeException ex) {
      System.err.println();
      System.err.println("Error for " + mediaFile);
      System.err.println(ex);
    }

    try {
      boolean interlaced = frameDetections.getSingle().isInterlaced();
      if (interlaced != frameDetections.getMulti().isInterlaced()) {
        throw new AmbiguousInterlacedStateException(mediaFile, frameDetections);
      }
      return interlaced;
    } catch (UnknownInterlacedStateException e) {
      throw new UnknownInterlacedStateException(mediaFile, e);
    }
  }
```

Notice the line with the FIXME comment with which I observe the behavior of the OutputListener.

When I switch from jaffree version 0.9.9 to 0.9.10 or higher, two things happen:

1. The OutputListener's return type changes from boolean to void -> easy to fix my calling code accordingly.
2. The OutputListener is no longer fed the entire output of ffmpeg. Instead. it now receives only one single line: "Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options". As a result, custom output parsing fails.

This single line is an error message from ffmpeg that I can ignore in my case. Because all other ffmpeg output is not handed to the OutputListener, the custom parsing no longer works.

Because I couldn't find any information that would indicate the calling code needs further changes besides the mentioned return type, I'm assuming this is a bug in the latest versions of Jaffree.

**Comment by kokorin** [comment]
Hello recently I changed FFmpeg output parsing and OutputListener
signature, for now you can downgrade Jaffree version.
I will have a chance to check it in a week.

чт, 25 февр. 2021 г., 21:07 skythor17 <notifications@github.com>:

**Comment by skythor17** [comment]
Sure, anything that helps find the issue.

This is an example command I trigger:
`ffmpeg.exe -i "test.TS" -y -filter idet -frames:v 100 -map 0:v:0 -c:v rawvideo -f null NUL`

Github won't let me attach a text file containing the ffmpeg output ("Something went really wrong, and we can't process that file"). I'll just paste it inline here instead. It's not as readable as the original, leading whitespace for indentation is gone.

> ffmpeg version git-2020-07-13-7772666 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 55.100 / 56. 55.100
  libavcodec     58. 95.100 / 58. 95.100
  libavformat    58. 48.100 / 58. 48.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[mpegts @ 0000028d38c23b40] probed stream 1 failed
[mpeg2video @ 0000028d38c49800] Invalid frame dimensions 0x0.
    Last message repeated 10 times
[mpegts @ 0000028d38c23b40] PES packet size mismatch
[mpegts @ 0000028d38c23b40] Packet corrupt (stream = 0, dts = 6926510426).
[mpegts @ 0000028d38c23b40] PES packet size mismatch
[mpegts @ 0000028d38c23b40] Packet corrupt (stream = 2, dts = 6926514026).
[mpegts @ 0000028d38c23b40] PES packet size mismatch
[mpegts @ 0000028d38c23b40] Packet corrupt (stream = 4, dts = 6926514921).
[mpegts @ 0000028d38c23b40] PES packet size mismatch
[mpegts @ 0000028d38c23b40] Packet corrupt (stream = 1, dts = 6926514950).
[mpegts @ 0000028d38c23b40] Could not find codec parameters for stream 1 (Unknown: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from 'test.TS':
  Duration: 00:00:09.20, start: 76952.557222, bitrate: 5176 kb/s
    Stream #0:0[0x29e]: Audio: mp2, 48000 Hz, stereo, s16p, 256 kb/s
    Stream #0:1[0x2a8]: Unknown: none
    Stream #0:2[0x2a0]: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
    Stream #0:3[0x294]: Video: mpeg2video (Main), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 15000000/0/0 buffer size: 1835008 vbv_delay: N/A
    Stream #0:4[0x2a3]: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Stream #0:5[0x29f]: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
Stream mapping:
  Stream #0:3 -> #0:0 (mpeg2video (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf58.48.100
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 720x576 [SAR 64:45 DAR 16:9], q=2-31, 124416 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.95.100 rawvideo
[Parsed_idet_0 @ 0000028d390eff80] Repeated Fields: Neither:    97 Top:     2 Bottom:     2
[Parsed_idet_0 @ 0000028d390eff80] Single frame detection: TFF:   101 BFF:     0 Progressive:     0 Undetermined:     0
[Parsed_idet_0 @ 0000028d390eff80] Multi frame detection: TFF:   101 BFF:     0 Progressive:     0 Undetermined:     0
