### ISSUE TITLE
Releasing resources used  by FFmpegResult

### ISSUE THREAD

**Issue by imvinaypatil** [kokorin/Jaffree#13]
If i try to delete the input file provided to the FFmpegResult instance after its execution will result  `java.nio.file.FileSystemException: The process cannot access the file because it is being used by another `process.
How can we gracefully release the resources programmatically  once the job is done ?

**Comment by kokorin** [comment]
Could you provide code sample?

**Comment by imvinaypatil** [comment]
No special code it's just the example code with added Files.delete
`Path BIN = Paths.get("C:\\ffmpeg\\shared\\bin");
        Path VIDEO_MP4 = Paths.get("C:\\Users\\team3\\Desktop\\User\\Vinay\\javacppffmpeg\\frame.avi");
        Path OUTPUT_MP4 = Paths.get("C:\\Users\\team3\\Desktop\\User\\Vinay\\javacppffmpeg\\frame.mp4");

        ProgressListener listener = new ProgressListener() {
            @Override
            public void onProgress(FFmpegProgress progress) {
                //TODO handle progress data
            }
        };


        FFmpegResult result = FFmpeg.atPath(BIN)
                .addInput(UrlInput.fromPath(VIDEO_MP4))
                .addOutput(UrlOutput.toPath(OUTPUT_MP4)
                )
                // This is optional
                .setProgressListener(listener)
                .execute();
        Files.delete(VIDEO_MP4);
`

`Caused by: java.lang.RuntimeException: File 'C:\Users\team3\Desktop\User\Vinay\javacppffmpeg\frame.mp4' already exists. Exiting.
	at com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader.read(FFmpegResultReader.java:83)
	at com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader.read(FFmpegResultReader.java:32)
	at com.github.kokorin.jaffree.process.ProcessHandler$1.run(ProcessHandler.java:108)`

**Comment by imvinaypatil** [comment]
Sorry my bad, found out the issue. It's my code (another thread) being holding the files. thanks for prompt reply though.
