### ISSUE TITLE
Decode MP4 I and P Frames

### ISSUE THREAD

**Issue by OrdenKrieger** [kokorin/Jaffree#130]
I have a question, I have an IP camera which sends MP4 I and P frames over UDP. Would it be possible with this plugin to pipe the received byte[] frames into FFmpeg? I was looking at the "Supplying and consuming data with InputStream and OutputStream" example but didn't get further with that.

**Comment by kokorin** [comment]
Probably you need just UrlInput with UDP address supplied. FFmpeg can
listen to UDP itself.

ср, 3 мар. 2021 г., 16:20 OrdenKrieger <notifications@github.com>:

**Comment by OrdenKrieger** [comment]
Hmm but the frames are encapsulated in the UDP packet with a proprietary header which I cut out so I'm left with just the frame as byte[]. Also is the camera only sending to my given IP address so it's not actually streaming under any URL.
