### ISSUE TITLE
Output to rtmp

### ISSUE THREAD

**Issue by BerndiVader** [kokorin/Jaffree#131]
Hello! How would i config the output to write to a rtmp destination? I managed to output to a local file only. Thanks. :)

**Comment by kokorin** [comment]
Hello. You should use `UrlOutput` with provided rtmp URL you want to stream to.
Of course it's better first to experiment with ffmpeg in console to better understand what options/arguments are required.

**Comment by BerndiVader** [comment]
Hi! Thanks, i will do so.
