### ISSUE TITLE
Cannot run the library on Ubuntu 

### ISSUE THREAD

**Issue by MohamedHassanKhames** [kokorin/Jaffree#145]
Do you have any idea why I got this error when I try to run this code? 
![Screenshot from 2021-04-25 13-05-18](https://user-images.githubusercontent.com/13554515/115989591-c4936100-a5c7-11eb-8d72-568594c8f251.png)

I get this error
![Screenshot from 2021-04-25 13-04-57](https://user-images.githubusercontent.com/13554515/115989602-d2e17d00-a5c7-11eb-8aa8-60d12647e91c.png)

**Comment by kokorin** [comment]
FFmpeg path, show logs

**Comment by MohamedHassanKhames** [comment]
FFmpeg path -> 
![ff](https://user-images.githubusercontent.com/13554515/115994675-ae45cf00-a5e0-11eb-84a7-9a76b666796c.png)

Here are the logs:
![Screenshot from 2021-04-25 16-09-11](https://user-images.githubusercontent.com/13554515/115994702-c289cc00-a5e0-11eb-9133-6d46050773d4.png)

**Comment by kokorin** [comment]
You can see the problem in loglevel message, update fflmpeg

**Comment by MohamedHassanKhames** [comment]
Thanks
