### ISSUE TITLE
Java module not found

### ISSUE THREAD

**Issue by RakSrinaNa** [kokorin/Jaffree#171]
Starting version `2021-03-31` I cannot import Jaffree as a module anymore :

```
1 actionable task: 1 executed
...\src\main\java\module-info.java:13: error: module not found: jaffree
	requires jaffree;
	         ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```

Using version `0.11.0` works fine and the module is found.

Am I the only one in that case where versions with the new naming scheme are not recognized as a module ?

Maybe the new naming of the jar file makes java unable to create an automatic module name. Adding the manifest attribute `Automatic-Module-Name` could maybe help ? (https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html#of-java.nio.file.Path...-)

**Comment by RakSrinaNa** [comment]
```bash
$ jar --file .\jaffree-2021-05-07.jar --describe-module
Unable to derive module descriptor for: .\jaffree-2021-05-07.jar
jaffree.2021.05: Invalid module name: '2021' is not a Java identifier
```

**Comment by kokorin** [comment]
What build tool do you use? Could you try with Java 8? To investigate this it would be great to have an example showing the problem.

**Comment by kokorin** [comment]
Seems you are right, after version pattern change Java9 can't automatically derive module from a jar. 
I found a [solution](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html) on maven site. Could you suggest another approach?

**Comment by kokorin** [comment]
Check `2021.05.26` version. It contains module-info.class, other classes are compiled with Java 8.
