### ISSUE TITLE
Consider making Filter an abstract type

### ISSUE THREAD

**Issue by viniciusccarvalho** [kokorin/Jaffree#182]
Hi there, not an issue per se. But I'm currently evaluating bringing this lib into our pipeline, and we are enjoying some of the neat benefits it provides vs using just java process to invoke ffmpeg.

One thing however, I know ffmpeg filters can be quite flexible, and the `Filter` type makes it easy to pretty much create any filter. But I wanted to start building a few typed filters `CropFilter` and `TrimFilter` that really should not expose things like setName ... I think that the fact that the Filter is both the type and the builder are making it a bit harder, so I wondered if you would be open to perhaps make `Filter` an interface and have a `FilterBuilder` to build general purpose filters, but allow users to expand and create their own typed Filters.

The alternative to that is provide static builders such as `public static Filter cropFilter()` but one thing I like about having strong types is the chance to for instance add validation on each filter for the arguments users passes to it.

Thank you

**Comment by kokorin** [comment]
@viniciusccarvalho thanks for the suggestion, it may be interesting.

It would be great to see a PR with such changes. I don't think its discussion will take too long, I believe in a week or two we could incorporate it into main branch.

The main problem I see with flexible filters is that some filters require input number for processing. I didn't want to bind `Filter` and `Input` (or `Output`). Anyway I believe it's possible.
