### ISSUE TITLE
getting string output form FFprobe

### ISSUE THREAD

**Issue by wojtess** [kokorin/Jaffree#189]
Hi.

is there any easier way to get String output, or Json Output from FFprobeResult, than this?

```
        FFprobeResult result = FFprobe.atPath()
                .setInput(com.github.kokorin.jaffree.ffprobe.UrlInput.fromPath(input))
                .addArguments("-v","quiet")
                .addArguments("-show_streams","")
                .addArguments("-select_streams","v:0")
                .execute();

        try {
            Field field = result.getData().getClass().getDeclaredField("data");
            field.setAccessible(true);
            System.out.println(field.get(result.getData()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
```

i think good idea is add some toString() function which returns some more usesful than `com.github.kokorin.jaffree.ffprobe.data.JsonFormatParser$ProbeDataJson@5b80350b`

Thanks for any response.

**Comment by kokorin** [comment]
Hello,

Consider using `FFprobeResult.getData()`. It will return `ProbeData` which contains a lot of methods to retrieve parsed data. To go one level down use `ProbeData.getSubData`.

**Comment by wojtess** [comment]
> Hello,
> 
> Consider using `FFprobeResult.getData()`. It will return `ProbeData` which contains a lot of methods to retrieve parsed data. To go one level down use `ProbeData.getSubData`.

Thanks for replay.

Is there option to get all this values?
If i wouldn't get `data` filed from `FFprobeResult.getData()` and print it i I wouldn't know what parameters i can get via `ProbeData.getSubData`.

**Comment by kokorin** [comment]
If you really need raw data you can implement your own ffprobe FormatParser.
But if I were you I would use existing JsonFormat with recursive approach.
