### ISSUE TITLE
ffmpeg location discovery in tests

### ISSUE THREAD

**Issue by kokorin** [kokorin/Jaffree#200]
The other thing that was a little confusing at first when I first tried to `mvn package` was that the unit tests use two different mechanisms to get the working `ffmpeg` binary:

1. some places rely on ffmpeg being configured on your PATH
2. other places rely on configuring the `FFMPEG_BIN` env var or Java system var

Is it intentional to have both? I suppose in theory you could then use 2 different versions.
I am thinking it might be helpful if I add some explanation in the README?

_Originally posted by @marklassau in https://github.com/kokorin/Jaffree/issues/197#issuecomment-891413765_

All tests should use the same mechanism for ffmpeg location discovery:
1. Try PATH env
2. If not found try FFMPEG_BIN env
3. Throw an exception

**Comment by kokorin** [comment]
@marklassau here is an issue

**Comment by marklassau** [comment]
It probably makes sense to reverse the order of precedence.
That is:

1. Look for an explicit FFMPEG_BIN var
2. If not found, expect ffmpeg to be on path
3. If none of these work, throw an exception

Agreed?

**Comment by kokorin** [comment]
Sure, thank you for the update
