### ISSUE TITLE
Arguments order are built incorrectly which causes ffmpeg throw excpetion

### ISSUE THREAD

**Issue by pkukharenka** [kokorin/Jaffree#204]
Simple code to cut part of the video without encoding:

>FFmpeg.atPath()
    addInput(
                          UrlInput
                                .fromUrl(pathToSrc)
                                .setPosition(10, TimeUnit.SECONDS)
                                .setDuration(42, TimeUnit.SECONDS)
                                .setCodec(StreamType.VIDEO, "copy")
                                .setCodec(StreamType.AUDIO, "copy")
                )
                .addOutput(
                        UrlOutput.toUrl(pathToDst)
                )
                .execute();

This will execute the next command:
`ffmpeg -loglevel level+info -t 42.000 -ss 10.000 -c:v copy -c:a copy -i <VIDEO_PATH> -n <DEST_PATH>`

ffmpeg will throw exception: **Unknown decoder 'copy'**

However if you just replace the order of arguments to:
`ffmpeg -i <VIDEO_PATH> -loglevel level+info -t 42.000 -ss 10.000 -c:v copy -c:a copy  -n <DEST_PATH>`

everything will work fine.

Bug in the buildArguments() method. BaseInput first calls buildArguments() of the parent class (BaseInOut) which adds all the arguments and only after that BaseInput adds input file. The input file should be added at first.

**Comment by kokorin** [comment]
@pkukharenka  the order of arguments is the same as you specify. The mistake is that FFmpeg input doesn't accept copy codec. Input codec is only useful if FFmpeg itself can't detect it.
Please, check FFmpeg documentation.

**Comment by kokorin** [comment]
Use `UrlOutput.setCodec` or just `UrlOutput.copyCodec`

**Comment by pkukharenka** [comment]
@kokorin yes, you are right. Thanks!
