### ISSUE TITLE
Get Frame timecode on FrameConsumer

### ISSUE THREAD

**Issue by comoroberto** [kokorin/Jaffree#220]
Hello.

I have to extract frames from a source video and store the timecode of each frame. (like each png filename must contain the timecode)

Have found this example:
https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/test/java/examples/ExtractFramesExample.java#L16

`FFmpegResultReader` has access to the timecode info but seems `FrameConsumer` and `Frame` model doesn't.

> [36mc.g.k.jaffree.ffmpeg.FFmpegResultReader [0;39m [2m:[0;39m [info] frame=    1 fps=0.0 q=-0.0 size=    1728kB time=00:00:00.00 bitrate=943963733.3kbits/s speed=0.00139x
> 
> [36mc.g.k.jaffree.ffmpeg.FFmpegResultReader [0;39m [2m:[0;39m [info] frame=    2 fps=0.0 q=-0.0 size=    3456kB time=00:00:10.00 bitrate=2831.5kbits/s dup=0 drop=139 speed=19.6x

There is any way to do that ?

**Comment by kokorin** [comment]
Hello, 

if you use `FrameConsumer` every `Frame` is assigned a timestamp (PTS).
Check  [`Frame#getPts()`](https://github.com/kokorin/Jaffree/blob/28ef48ce01acfabab3a3219236a291cb654e644c/src/main/java/com/github/kokorin/jaffree/ffmpeg/Frame.java#L79):

```java
    /**
     * PTS in corresponding {@link Stream} timebase.
     * E.g. Track's timebase is 44100 (audio track), timecode is 4410 - it means 0.1 second
     * (100 milliseconds)
     *
     * @return timecode
     * @see Stream#getTimebase()
     */
    public long getPts() {
        return pts;
    }
```

**Comment by comoroberto** [comment]
Thanks. I have some doubts about how to interpret timebase returned by  [`Frame#getPts()`](https://github.com/kokorin/Jaffree/blob/28ef48ce01acfabab3a3219236a291cb654e644c/src/main/java/com/github/kokorin/jaffree/ffmpeg/Frame.java#L79)

Framerate is 25. PTS is 3932160. How can i get second ?

**Comment by kokorin** [comment]
`timestmap = PTS/framerate`

So in your case it's `3,932,160/25 = 157,286.4 ~ 43 hours 41 minute`

**Comment by comoroberto** [comment]
That's the point. `3932160` is the first frame that i had got using `0.1` as sample rate with a 25 fps source video.

https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/test/java/examples/ExtractFramesExample.java#L62

Comparing with the video, the frame should be in the interval 20-25 seconds but `getPts(`) returns `3932160` . 😅

**Comment by kokorin** [comment]
In that case probably you are talking about audio frames. Anyway double check above mentioned javadoc, it says Stream timebase, which may not ( in case of audio stream can not) coincide with frame rate.

To get a stream use the other method in FrameOutput.

**Comment by comoroberto** [comment]
I'm refering to video frame, from you example code [ExtractFramesExample.java](https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/test/java/examples/ExtractFramesExample.java) but using `Frame#getPts()` for generate the file name.

So this is the code of the FrameConsumer

```java
FrameConsumer frameConsumer = new FrameConsumer() {
            @Override
            public void consumeStreams(List<Stream> streams) {
                // All stream type except video are disabled. just ignore
            }

            @Override
            public void consume(Frame frame) {
                // End of Stream
                if (frame == null) {
                    return;
                }

                try {
                    String filename = "frame_" + frame.getPts() + ".png";
                    Path output = pathToDstDir.resolve(filename);
                    ImageIO.write(frame.getImage(), "png", output.toFile());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
```


For the first frame extracted, `frame.getPts()` evaluates `0` and its correct because is the start frame.
For the second frame, `frame.getPts()` evaluates `3932160` and i cannot understand how i have to manage this value.

That's the source video file:

```
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 280 MiB
Duration                                 : 20 min 51 s
Overall bit rate                         : 1 875 kb/s
Writing application                      : Lavf58.43.100

Video
ID                                       : 3
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 20 min 51 s
Bit rate                                 : 1 674 kb/s
Nominal bit rate                         : 1 800 kb/s
Width                                    : 1 024 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.114
Stream size                              : 250 MiB (89%)
Writing library                          : x264 core 160 r3000 33f9e14
Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=1 / b_pyramid=0 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=25 / keyint_min=13 / scenecut=40 / intra_refresh=0 / rc_lookahead=25 / rc=abr / mbtree=1 / bitrate=1800 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / ip_ratio=1.41 / aq=1:1.00
Codec configuration box                  : avcC

Audio #1
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 20 min 51 s
Duration_LastFrame                       : -20 ms
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 14.3 MiB (5%)
Language                                 : Italian
Default                                  : Yes
Alternate group                          : 1

Audio #2
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 20 min 51 s
Duration_LastFrame                       : -20 ms
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 14.3 MiB (5%)
Language                                 : des
Default                                  : No
Alternate group                          : 1
```


The source file has a duration of about 21 minute. How i can get `3932160` that with a framerate of 25 should be `~ 43 hours 41 minute`?

**Comment by kokorin** [comment]
> The source file has a duration of about 21 minute. How i can get 3932160 that with a framerate of 25 should be ~ 43 hours 41 minute?

It can't be, you miss stream timebase and FPS! 

Method `consumeStreams` is exactly for you to check `Stream` information. Probably the comment "just ignore" tricked you: it describes only the example, not whole approach to frame consumption.

```java
            @Override
            public void consumeStreams(List<Stream> streams) {
                // 
            }
```

Share the file and sample project.

**Comment by comoroberto** [comment]
- Timebase: `51200`
- original source FPS: `25`
- [FrameOutput#setFrameRate()](https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/main/java/com/github/kokorin/jaffree/ffmpeg/BaseInOut.java#L190): `0.1`
- [Frame#getPts()](https://github.com/kokorin/Jaffree/blob/28ef48ce01acfabab3a3219236a291cb654e644c/src/main/java/com/github/kokorin/jaffree/ffmpeg/Frame.java#L79): `3932160`

Timecode of the frame: `?`

I will try to share the source file. Thanks. 👍

**Comment by kokorin** [comment]
Please, if you need help, whole information. Earlier you wrote there are 3 streams in a file. And now you give some numbers out of the blue and want clarification.

**Comment by comoroberto** [comment]
The use case is always to extract frames from a video stream. :slightly_smiling_face: 

To achieve that i'm using the example [ExtractFramesExample.java](https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/test/java/examples/ExtractFramesExample.java) but using` Frame#getPts()` for generate the file name.

```` java
 public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Exactly 2 arguments expected: path to source file"
                    + " and destination directory");
            System.exit(1);
        }

        Path pathToSrc = Paths.get(args[0]);
        final Path pathToDstDir = Paths.get(args[1]);

        FFmpeg.atPath()
                .addInput(UrlInput
                        .fromPath(pathToSrc)
                )
                .addOutput(FrameOutput
                        .withConsumer(
                                new FrameConsumer() {
       
                                    @Override
                                    public void consumeStreams(List<Stream> streams) {
                                        // All stream type except video are disabled. just ignore
                                    }

                                    @Override
                                    public void consume(Frame frame) {
                                        // End of Stream
                                        if (frame == null) {
                                            return;
                                        }

                                        try {
                                            String filename = "frame_" + frame.getPts() + ".png";
                                            Path output = pathToDstDir.resolve(filename);
                                            ImageIO.write(frame.getImage(), "png", output.toFile());
                                        } catch (Exception e) {
                                            e.printStackTrace();
                                        }
                                    }
                                }
                        )
                        // No more then 100 frames
                        .setFrameCount(StreamType.VIDEO, 100L)
                        // 1 frame every 10 seconds
                        .setFrameRate(0.1)
                        // Disable all streams except video
                        .disableStream(StreamType.AUDIO)
                        .disableStream(StreamType.SUBTITLE)
                        .disableStream(StreamType.DATA)
                )
                .execute();
    }
````


The input source is a mp4 file, with 3 stream of which 1 video and 2 audios.

So the stream consumed by FrameOutput FrameConsumer is the video stream with this meta on the previous comment.

My question is how the PTS value has to be interpreted.

You said:

> timestmap = PTS/framerate

> It can't be, you miss stream timebase and FPS!

So initially i didn't think the timebase value was related, and still now i don't understand how to get timestamp value so i have wrote some real example values of PTS, original framerate of video stream and frame rate value used in `.setFrameRate()` method.

Like wrote on meta of previous post, the stream video source has a frame rate of `25 FPS`.

[FrameOutput#setFrameRate()](https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/main/java/com/github/kokorin/jaffree/ffmpeg/BaseInOut.java#L190) value is `0.1`

[FrameConsumer#consumeStreams](https://github.com/kokorin/Jaffree/blob/6603682b12dc64997611dc3895645ec5ef916c3d/src/main/java/com/github/kokorin/jaffree/ffmpeg/FrameConsumer.java#L32) is invoked with `List<Stream> streams` of 1 element, the video stream.
`streams.get(0).getTimebase()` evaluate  `51200`

In the first occurrence of the invoke of the method [FrameConsumer#consume(Frame frame)](url), frame.getPts() evaluates `0`.
It's the first frame of the video stream, timecode 00:00:00. That's ok.

In the second occurrence of the invoke of the method [FrameConsumer#consume(Frame frame)](url), frame.getPts() evaluates [3932160](url).

I need some help to understand how to get timecode value from `3932160`. 👍

**Comment by kokorin** [comment]
Please, stop quoting ExtractFrameExample. 
Let me cite myself:

>Anyway double check above mentioned javadoc, it says Stream timebase, which may not ( in case of audio stream can not) coincide with frame rate.
>
>To get a stream use the other method in FrameOutput.

**Stream timebase** (there is even a link to Stream class, not ffprobe Stream, but ffmpeg)

> Method consumeStreams is exactly for you to check Stream information. Probably the comment "just ignore" tricked you: it describes only the example, not whole approach to frame consumption.

You wrote:
> I need some help to understand how to get timecode value from 3932160. 👍

**Please, collect all information I asked**. Otherwise I can't help you: you just give me the same figures over and over again. There is no magical constant which can describe how 3932160 PTS can become 0.1 second.

The formula is simple (this time correct): `TS = PTS/TimeBase`. If it's not clear, please read corresponding articles.

**Comment by comoroberto** [comment]
> Please, collect all information I asked. Otherwise I can't help you: you just give me the same figures over and over again. There is no magical constant which can describe how 3932160 PTS can become 0.1 second.

I think to that i have given all of that. What's missing ?


> The formula is simple (this time correct): TS = PTS/TimeBase.

Now sounds good.
