### ISSUE TITLE
Problems with the default ffmpeg installation

### ISSUE THREAD

**Issue by eGit** [kokorin/Jaffree#227]
**Describe the issue**
I use my own locally downloaded ffmpeg binary and define it in atPath(...) without issues.

However since I am on Linux Mint 17.3, there is already ffmpeg installed at /usr/bin/ffmpeg

I use /usr/bin/ffmpeg quite often without any problems.

> /usr/bin/ffmpeg
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

However when I leave atPath() empty OR add the location atPath(Paths.get("/usr/bin/")) it doesn't work:

> [main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Command constructed:
/usr/bin/ffmpeg -loglevel level+info -i "/mnt/files/video.mp4" -n -progress tcp://127.0.0.1:43395 -f null -c copy /dev/null
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Starting process: /usr/bin/ffmpeg
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Waiting for process to finish
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Process has finished with status: 1
[StdErr] INFO com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader - Invalid loglevel "level+info". Possible levels are numbers or:
"quiet"
"panic"
"fatal"
"error"
"warning"
"info"
"verbose"
"debug"
"trace"
[main] WARN com.github.kokorin.jaffree.process.ProcessHandler - Executor hasn't stopped in 10000 millis, won't wait longer
[main] WARN com.github.kokorin.jaffree.process.Executor - Interrupting ALIVE thread: Runnable-0
Exception in thread "main" com.github.kokorin.jaffree.JaffreeException: Process execution has ended with non-zero status: 1
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:201)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:146)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at examples.ExactDurationExample.main(ExactDurationExample.java:42)

Also of note, there is this logging error: "level+info"

**Comment by kokorin** [comment]
Hello @eGit ,
The problem is in ffmpeg version, as the error says:
```
Invalid loglevel "level+info"
```
Jaffree relies on structured ffmpeg output, so this option is required.
