### ISSUE TITLE
Image written out at wrong timestamp argument

### ISSUE THREAD

**Issue by eGit** [kokorin/Jaffree#229]
When I write out an image using Streams and use a timestamp, I actually write out an image ~10 seconds into the future of the timestamp I specified.

This is a problem using InputStream. When I use UrlInput.fromPath it outputs the correct timestamp.

> public class ExtractBitmap2 {
    public static void main(String[] args) throws Exception {
    	
    	Path path = Paths.get("/mnt/Data/software/ffmpeg-git-20210908-amd64-static");
    	args = new String[] {"/mnt/files/input.mkv", "/mnt/files/bitmap.jpg"};
    	
        Path pathToSrc = Paths.get(args[0]);

        try (InputStream inputStream =
                     Files.newInputStream(pathToSrc);
        ) {
            FFmpeg.atPath(path)
			.addInput(PipeInput.pumpFrom(inputStream).setPosition(60 * 1000))
			.addArguments("-frames:v", "1")
    		.addArguments("-q:v", "1")
                    .addOutput(UrlOutput.toUrl("/mnt/Data/downloads/direct.jpeg"))
                    .execute();
        }
    }
}

**Comment by kokorin** [comment]
Of course, there is a difference between the 2 approaches. And there are a lot of things that can influence on that: keyframes, size, metainf location and much more.

You can try to do the same with OS pipes ( `|` symbol). I'm sure you will get the same result.
One should understand that InputStreams are non-seekable by their nature, while local files are seekable. 

And again: it's not an issue with Jaffree.  Closing.

**Comment by kokorin** [comment]
With `InputStream` it can't be done with 100% reliability. Check an option in ffmpeg for exact positioning.
Read this: http://trac.ffmpeg.org/wiki/Seeking
Use `ChannelInput` if you can, it allows seeking.
