### ISSUE TITLE
Gracefully parse ffmpeg and ffprobe output

### ISSUE THREAD

**Issue by shoeoffhead** [kokorin/Jaffree#230]
For some video files ffmpeg and ffprobe outputs a single strange logging line where your parser throws an Exception. One could argue that the parser should detect such cases and just ignore them since the rest of the output is just fine.

In the below output this line forces your FFProbeLogReader into aborting the parsing:
[flv @ 0x6348840] [error] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0

> ffprobe -loglevel level+verbose -show_format -show_streams -show_private_data -print_format json -i /mnt/Data/test/test.flv
[info] ffprobe version 4.4-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
[info]   built with gcc 8 (Debian 8.3.0-6)
[info]   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
[info]   libavutil      56. 70.100 / 56. 70.100
[info]   libavcodec     58.134.100 / 58.134.100
[info]   libavformat    58. 76.100 / 58. 76.100
[info]   libavdevice    58. 13.100 / 58. 13.100
[info]   libavfilter     7.110.100 /  7.110.100
[info]   libswscale      5.  9.100 /  5.  9.100
[info]   libswresample   3.  9.100 /  3.  9.100
[info]   libpostproc    55.  9.100 / 55.  9.100
{
[flv @ 0x6348840] [error] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[info] Input #0, flv, from '/mnt/Data/test/test.flv':
[info]   Metadata:
[info]     metadatacreator : Yet Another Metadata Injector for FLV - Version 1.2
[info]     hasKeyframes    : true
[info]     hasVideo        : true
[info]     hasAudio        : true
[info]     hasMetadata     : true
[info]     canSeekToEnd    : false
[info]     datasize        : 20047517
[info]     videosize       : 16856472
[info]     audiosize       : 3136113
[info]     lasttimestamp   : 258
[info]     lastkeyframetimestamp: 252
[info]     lastkeyframelocation: 19625132
[info]   Duration: 00:04:17.93, start: 0.000000, bitrate: 621 kb/s
[info]   Stream #0:0: Video: flv1, 1 reference frame, yuv420p, 480x360, 521 kb/s, 14.96 fps, 14.99 tbr, 1k tbn
[info]   Stream #0:1: Audio: mp3, 44100 Hz, stereo, fltp, 93 kb/s
    "streams": [
        {
            "index": 0,
            "codec_name": "flv1",
            "codec_long_name": "FLV / Sorenson Spark / Sorenson H.263 (Flash Video)",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 480,
            "height": 360,
            "coded_width": 480,
            "coded_height": 360,
            "closed_captions": 0,
            "has_b_frames": 0,
            "pix_fmt": "yuv420p",
            "level": -99,
            "refs": 1,
            "r_frame_rate": "15000/1001",
            "avg_frame_rate": "703/47",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bit_rate": "521500",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        },
        {
            "index": 1,
            "codec_name": "mp3",
            "codec_long_name": "MP3 (MPEG audio layer 3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bit_rate": "93899",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ],
    "format": {
        "filename": "/mnt/Data/test/test.flv",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "flv",
        "format_long_name": "FLV (Flash Video)",
        "start_time": "0.000000",
        "duration": "257.933000",
        "size": "20048757",
        "bit_rate": "621828",
        "probe_score": 100,
        "tags": {
            "metadatacreator": "Yet Another Metadata Injector for FLV - Version 1.2",
            "hasKeyframes": "true",
            "hasVideo": "true",
            "hasAudio": "true",
            "hasMetadata": "true",
            "canSeekToEnd": "false",
            "datasize": "20047517",
            "videosize": "16856472",
            "audiosize": "3136113",
            "lasttimestamp": "258",
            "lastkeyframetimestamp": "252",
            "lastkeyframelocation": "19625132"
        }
    }[AVIOContext @ 0x6351880] [verbose] Statistics: 262144 bytes read, 0 seeks

}

> [main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Command constructed:
/mnt/Data/software/ffmpeg-4.4-amd64-static/ffprobe -loglevel level+verbose -show_format -show_streams -show_private_data -print_format json -i /mnt/Data/test/test.flv
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Starting process: /mnt/Data/software/ffmpeg-4.4-amd64-static/ffprobe
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Waiting for process to finish
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info] ffprobe version 4.4-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
[main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Process has finished with status: 0
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   built with gcc 8 (Debian 8.3.0-6)
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libavutil      56. 70.100 / 56. 70.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libavcodec     58.134.100 / 58.134.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libavformat    58. 76.100 / 58. 76.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libavdevice    58. 13.100 / 58. 13.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libavfilter     7.110.100 /  7.110.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libswscale      5.  9.100 /  5.  9.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libswresample   3.  9.100 /  3.  9.100
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   libpostproc    55.  9.100 / 55.  9.100
[StdErr] ERROR com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [flv @ 0x6b9a440] [error] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info] Input #0, flv, from '/mnt/Data/test/test.flv':
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   Metadata:
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     metadatacreator : Yet Another Metadata Injector for FLV - Version 1.2
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     hasKeyframes    : true
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     hasVideo        : true
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     hasAudio        : true
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     hasMetadata     : true
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     canSeekToEnd    : false
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     datasize        : 20047517
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     videosize       : 16856472
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     audiosize       : 3136113
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     lasttimestamp   : 258
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     lastkeyframetimestamp: 252
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]     lastkeyframelocation: 19625132
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   Duration: 00:04:17.93, start: 0.000000, bitrate: 621 kb/s
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   Stream #0:0: Video: flv1, 1 reference frame, yuv420p, 480x360, 521 kb/s, 14.96 fps, 14.99 tbr, 1k tbn
[StdErr] INFO com.github.kokorin.jaffree.ffprobe.FFprobeLogReader - [info]   Stream #0:1: Audio: mp3, 44100 Hz, stereo, fltp, 93 kb/s
[StdErr] WARN com.github.kokorin.jaffree.process.Executor - Interrupting starter thread (main) because of exception: Finished with error message: [flv @ 0x6b9a440] [error] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
[main] WARN com.github.kokorin.jaffree.process.ProcessHandler - Process has been interrupted
[main] WARN com.github.kokorin.jaffree.process.Executor - Interrupting ALIVE thread: StdOut
Exception in thread "main" com.github.kokorin.jaffree.JaffreeException: Failed to execute, was interrupted
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:189)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:146)
	at com.github.kokorin.jaffree.ffprobe.FFprobe.execute(FFprobe.java:549)
	at tool.Tree$VideoInfo.<init>(Tree.java:177)
	Suppressed: com.github.kokorin.jaffree.JaffreeException: Finished with error message: [flv @ 0x6b9a440] [error] Missing AMF_END_OF_OBJECT in AMF_DATA_TYPE_MIXEDARRAY, found 0
		at com.github.kokorin.jaffree.ffprobe.FFprobeLogReader.read(FFprobeLogReader.java:96)
		at com.github.kokorin.jaffree.ffprobe.FFprobeLogReader.read(FFprobeLogReader.java:37)
		at com.github.kokorin.jaffree.process.ProcessHandler$1.run(ProcessHandler.java:233)
		at com.github.kokorin.jaffree.process.Executor$1.run(Executor.java:83)
		at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.github.kokorin.jaffree.process.ProcessHandler.waitForExecutorToStop(ProcessHandler.java:318)
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:182)
	... 6 more

**Comment by shoeoffhead** [comment]
More lines in other video files ffprobe is writing out:
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5b55840] [error] Referenced QT chapter track not found
[h264 @ 0x5b57980] [verbose] Reinit context to 1280x720, pix_fmt: yuv420p

**Comment by kokorin** [comment]
#232 merged to develop, closing.
