### ISSUE TITLE
Read and write MP3 metadata (id3tag)

### ISSUE THREAD

**Issue by ahs441** [kokorin/Jaffree#247]
**Describe the issue**
Is there any way to read and write MP3 file tags, like artist, album, ...

**Comment by kokorin** [comment]
Sure it's possible, ffprobe wrapper parses whole output. How would you do it with pure command line?

**Comment by ahs441** [comment]
Can you give me any code example or documentation?

**Comment by kokorin** [comment]
First of all you need ffprobe command line:

```sh
ffprobe -show_streams  https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3
```

With Jaffree:

```java
String encoder = FFprobe.atPath()
  .setShowStreams(true)
  .setInput("https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3")
  .execute()
  .getStreams().get(0)
  .getTag("encoder");
```

Check examples in README.
