### ISSUE TITLE
Image and audio file streaming

### ISSUE THREAD

**Issue by joyzhang2022** [kokorin/Jaffree#248]
hi, 
I want to stream a picture and an mp3 file to rtmp server. I used the ffmpeg command before, which is written like this: 
`ffmpeg -re -framerate 1 -loop 1 -i image.jpg -stream_loop -1 -i audio.mp3 -c:v libx264 -preset ultrafast -c:a copy- f flv rtmp://`. 
I’m not sure if this is the best usage, but there is a problem. An error may occur after a few hours, and it will be troublesome to open it manually. 
Can you tell me how to implement this with code?  and automatically restart when an error occurs
```java
FFmpegResult result = FFmpeg.atPath()
                .addInput(UrlInput.fromUrl("/image.jpg")
                        .setFrameRate(1)
                        .addArgument("-re"))
                .addInput(UrlInput.fromUrl("/audio.mp3")
                        .addArgument("-re"))
                .addOutput(UrlOutput.toUrl("rtmp://").setFormat("flv"))
                .execute();
```
Thank you

**Comment by kokorin** [comment]
I would wrap the same code with while(true)

**Comment by joyzhang2022** [comment]
> I would wrap the same code with while(true)

```java
FFmpegResult result = FFmpeg.atPath()
                .addInput(UrlInput.fromUrl("/image.jpg")
                        .setFrameRate(1)
                        .addArgument("-re"))
                .addInput(UrlInput.fromUrl("/audio.mp3")
                        .addArgument("-re"))
                .addOutput(UrlOutput.toUrl("rtmp://").setFormat("flv"))
                .execute();
```

I used the above code to push to youtube, but it didn’t work. Why?
`
19:47:00.481 [StdErr] INFO com.github.kokorin.jaffree.process.BaseStdReader - [info] frame=    1 fps=0.0 q=10.1 size=    1757kB time=00:01:48.14 bitrate= 133.1kbits/s speed=0.999x    
19:47:00.994 [StdErr] INFO com.github.kokorin.jaffree.process.BaseStdReader - [info] frame=    1 fps=0.0 q=10.1 size=    1765kB time=00:01:48.67 bitrate= 133.1kbits/s speed=0.999x    
19:47:01.296 [StdErr] INFO com.github.kokorin.jaffree.process.BaseStdReader - [info] frame=    1 fps=0.0 q=10.1 size=    1773kB time=00:01:49.16 bitrate= 133.1kbits/s speed=0.999x    
19:47:01.296 [StdErr] WARN com.github.kokorin.jaffree.process.BaseStdReader - [flv @ 0x7fdc4dc07100] [warning] Failed to update header with correct duration.
19:47:01.296 [StdErr] WARN com.github.kokorin.jaffree.process.BaseStdReader - [flv @ 0x7fdc4dc07100] [warning] Failed to update header with correct filesize.
19:47:01.300 [StdErr] INFO com.github.kokorin.jaffree.process.BaseStdReader - [info] frame=    1 fps=0.0 q=10.1 Lsize=    1941kB time=00:01:49.53 bitrate= 145.2kbits/s speed=   1x    
19:47:01.305 [StdErr] INFO com.github.kokorin.jaffree.process.BaseStdReader - [info] video:164kB audio:1712kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.511529%
19:47:01.305 [StdOut] DEBUG com.github.kokorin.jaffree.process.Executor - StdOut thread has finished
19:47:01.307 [main] INFO com.github.kokorin.jaffree.process.ProcessHandler - Process has finished with status: 0
19:47:01.307 [main] DEBUG com.github.kokorin.jaffree.process.ProcessHandler - Waiting for Executor to stop
19:47:01.309 [StdErr] DEBUG com.github.kokorin.jaffree.process.Executor - StdErr thread has finished
19:47:01.412 [main] DEBUG com.github.kokorin.jaffree.process.Executor - Stopping execution
`

**Comment by kokorin** [comment]
First of all you need to check  if the problem appears with command line. I would bet that the issue is that you try to use an image as video input. ffmpeg treats images and video streams with single frame, i.e. you video stream duration is 1 second.
