### ISSUE TITLE
On CentOS command line not working

### ISSUE THREAD

**Issue by hope4555** [kokorin/Jaffree#249]
**Describe the issue**
FFprobe fails on CentOS

**To Reproduce**

 FFprobeResult result = FFprobe.atPath()
                    .setShowStreams(true)
                    .setCountPackets(false)
                    .setShowLog(LogLevel.QUIET)
                    .setLogLevel(LogLevel.QUIET)
                    .setAnalyzeDuration(15, TimeUnit.SECONDS)
                    .setInput(filePath)
                    .execute();

this is the resulting command line
ffprobe -loglevel level+quiet -show_log -8 -show_streams -show_private_data -analyzeduration 15000000 -print_format json -i /root/maayan/media/e421c36a-c3da-456c-b7b7-7ecc515523aa/source.mp4

2021-11-23 16:10:30.659  INFO 12275 --- [         StdErr] c.g.k.jaffree.process.BaseStdReader      : Invalid loglevel "level+quiet". Possible levels are numbers or:
"quiet"
"panic"
"fatal"
"error"
"warning"
"info"
"verbose"
"debug"
"trace"

ffprobe version 3.4.9 

**Sample file**
If applicable, attach a file with which the issue can be reproduced

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

**Comment by kokorin** [comment]
Update ffmpeg: `-loglevel level+quiet` isn't supported by old versions, but it is required for Jaffree to parse output.
