### ISSUE TITLE
RTSP Streaming

### ISSUE THREAD

**Issue by darkfrog26** [kokorin/Jaffree#256]
I'm attempting to stream from webm data coming from the browser through ffmpeg to an RTSP stream (the command-line working example: `"ffmpeg -follow 1 -rw_timeout 1000000 -f webm -i test.webm -c copy -f rtsp rtsp://localhost:8554/mystream"`), but it's unclear how to do some of the things I'm attempting. This is what I have:

```java
FFmpeg
                                  .atPath()
                                  .addArguments("-rw_timeout", "1000000")
                                  .addInput(PipeInput.pumpFrom(in))
                                  .addOutput(UrlOutput.toUrl("rtsp://localhost:8554/mystream"))
                                  .execute()
```

Where `in` is a `PipedInputStream`. However, I'm not even able to get a clear error message because I only get: `com.github.kokorin.jaffree.JaffreeException: Process execution has ended with non-zero status: 1. Check logs for detailed error message.` which tells me nothing about why the error happened and there are no logs for me to look at.

Any insights here would be appreciated.

**Comment by kokorin** [comment]
```java
FFmpeg
   .atPath()                                  
   .addInput(
          PipeInput.pumpFrom(in)
                       .addArguments("-rw_timeout", "1000000")
                       // other arguments
    )
   .addOutput(UrlOutput.toUrl("rtsp://localhost:8554/mystream"))
   .execute()
```

**Comment by darkfrog26** [comment]
@kokorin thanks!

**Comment by kokorin** [comment]
Welcome, you can find other snippets in examples.
