### ISSUE TITLE
image2pipe Usage

### ISSUE THREAD

**Issue by webfolderio** [kokorin/Jaffree#266]
I have an app that produces jpg images (files) and want to convert the these images to video file.
I Can't find a solution to feed Input data.
One solution collecting the images to a List and feeding pipe with SequenceInputStream.
But this solution consumes lot's of memory.
Is there an better to feed input continuously.

**Comment by kokorin** [comment]
I'm not sure what you mean by `SequenceInputStream`, but there are 2 ways to create video file from a set of images with ffmpeg and Jaffree:
1. Read files with fffmpeg: https://trac.ffmpeg.org/wiki/Slideshow
This way is optimal for performance if you control file naming.
2. Read images with `javax.imageio.ImageIO`.  You don't need to read all files at a time. It's better to read on by one and pass `BufferedImage` to Jaffree
See example here: https://github.com/kokorin/Jaffree/blob/master/src/test/java/examples/ProduceVideoExample.java 
```java
        FrameProducer producer = new FrameProducer() {
            private long frameCounter = 0;

            @Override
            public List<Stream> produceStreams() {
                return Collections.singletonList(new Stream()
                        .setType(Stream.Type.VIDEO)
                        .setTimebase(1000L)
                        .setWidth(320)
                        .setHeight(240)
                );
            }

            @Override
            public Frame produce() {
                BufferedImage image = ImageIO.read(...);
                long pts = frameCounter * 1000 / 10; // Frame PTS in Stream Timebase, 10 frames per second
                Frame videoFrame = Frame.createVideoFrame(0, pts, image);
                frameCounter++;
                return videoFrame; // return null when done
            }
        };
```

**Comment by webfolderio** [comment]
Thanks for the code snippet.
I will go with slideshow suggestion.
My app produces hunderes of images file and second solution is not memory efficent for my use case.

Thanks
