### ISSUE TITLE
Is it possible to save a screen capture as a new file and manually terminate the recording? 

### ISSUE THREAD

**Issue by spectacularcrackers** [kokorin/Jaffree#291]
Hello, 
I am attempting to modify the example ScreenCapture file. Unfortunately, I ran into a few issues: 

**I) Saving file**
Is it possible to save a screen capture as a new file (in an mp4 format) rather than modifying an existing file in the directory? 

**II) stopping the recording**
I would also like to be able to manually terminate the recording instead of it auto stopping after a set time. Is this possible 

Do you have an example of what this would look like?

**Comment by kokorin** [comment]
Hello,

i) Please, check this [example](https://github.com/kokorin/Jaffree/blob/master/src/test/java/examples/ScreenCaptureExample.java) again. It records screen to a file with ultrafast preset to minimize CPU load. After that recorded file is transcoded with better compression (to minimize file size)

ii) It is possible to stop screen recording:
```java
FFmpegResultFuture future = ffmpeg.executeAsync();
Thread.sleep(5_000);
future.graceStop();
```
[Example](https://github.com/kokorin/Jaffree/blob/master/src/test/java/examples/StopExample.java)

**Comment by spectacularcrackers** [comment]
Thanks for the quick reply. 

When I tried executing the transcoding code in the example file, I am getting the following error: Do you have any suggestions on resolving it? I am not sure which of my settings are incorrect 

Also, what is the setting to encode it into an **mp4** format? 

Code: 
```
        Path pathToOptimized = pathToVideo.resolveSibling("optimized-" + pathToVideo.getFileName());
        FFmpeg.atPath()
                .addInput(UrlInput.fromPath(pathToVideo))
                .addOutput(UrlOutput.toPath(pathToOptimized))
                .execute();

        Files.move(pathToOptimized, pathToVideo, StandardCopyOption.REPLACE_EXISTING);
    }
```

Error: 
```
Exception in thread "main" com.github.kokorin.jaffree.JaffreeException: Process execution has ended with non-zero status: 1. Check logs for detailed error message.
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:202)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:147)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.sc.ScreenCaptureExample.main(ScreenCaptureExample.java:73)
```

**Comment by spectacularcrackers** [comment]
Where should I set the extension to mp4? In the addOutput? `.setFormat("mp4")`?

Here is the log file
[Log_file.txt](https://github.com/kokorin/Jaffree/files/8391100/Log_file.txt)

**Comment by spectacularcrackers** [comment]
I am running the ScreenCaptureExample.java file. When I do UrlOutput.toPath("filename.**mp4**"), a file gets recorded, but it is unplayable. It is stuck at 0 seconds long, but the file size is large. 

When using UrlOutput.toPath("filename.**avi**"), it records fine. Is it possible to convert the avi file to mp4 after recording is done?

**Comment by spectacularcrackers** [comment]
Could you provide an overview of what the StopExample methods do? 

My goal is to have two ways of stopping the screen recording: 
a) when the recording duration is met 
b) when the application closes before the set duration is met. 

currently when the application closes before the set time duration is reached, the application stops but the screen keeps getting recorded.

**Comment by kokorin** [comment]
> I am running the ScreenCaptureExample.java file. When I do UrlOutput.toPath("filename.**mp4**"), a file gets recorded, but it is unplayable. It is stuck at 0 seconds long, but the file size is large.
> 
> When using UrlOutput.toPath("filename.**avi**"), it records fine. Is it possible to convert the avi file to mp4 after recording is done?

Because MP4 doesn't support streaming. You can find a lot of articles regarding that.



> Could you provide an overview of what the StopExample methods do?
> 
> My goal is to have two ways of stopping the screen recording: a) when the recording duration is met b) when the application closes before the set duration is met.
> 
> currently when the application closes before the set time duration is reached, the application stops but the screen keeps getting recorded.

`StopExample` stops ffmpeg with several different ways. README contains more information.

ffmpeg is executed in a child process, so it should stop when parent application stops. With Jaffree you can specify max recording length and call `FFmpeg.graceStop` later.

I would suggest you to experiment with ffmpeg CLI before implementing something with Jaffree. One should understand that Jaffree is CLI wrapper, so CLI understanding is required.

**Comment by kokorin** [comment]
No response, closing
