### ISSUE TITLE
use the example: Cut and scale media file, but it doesn't work

### ISSUE THREAD

**Issue by lye2018** [kokorin/Jaffree#303]
# this is my code:
```
        String rtspUrl = "rtsp://admin:qwer1234@192.168.1.163:554/LiveMedia/ch1/Media1";
        String filePath = "E:\\data\\MP4\\" + "20221111" + ".mp4";
        FFmpegResultFuture fFmpegResultFuture = FFmpeg.atPath()
                .addInput(
                        UrlInput.fromUrl(rtspUrl)
                                .setPosition(10, TimeUnit.SECONDS)
                                .setDuration(20, TimeUnit.SECONDS)
                )
                .setFilter(StreamType.VIDEO, "scale=160:-2")
                .setOverwriteOutput(true)
                .addArguments("-movflags", "faststart")
                .addOutput(
                        UrlOutput.toUrl(filePath)
                                .setPosition(10, TimeUnit.SECONDS)
                )
                .executeAsync();
```
this can not produce a new file 20221111.mp4，please help me thanks

**Comment by kokorin** [comment]
What's the error? Any logs? Did you intentionally ignore issue template? Please, help me to help you. Thanks.

**Comment by lye2018** [comment]
i am sorry deeply! these logs you can see from the picture, sorry! i am not intentional, i am just a kind rookie
![5c175e76afe8400dbeedec26650162c](https://user-images.githubusercontent.com/42856412/168958843-2569c200-b4ef-4114-8537-737592d89ede.png)

**Comment by kokorin** [comment]
Sorry, but that's not enough. Please copy-paste whole log in text format.

**Comment by lye2018** [comment]
All logs in the txt files.
maybe i need do something configuration about ffmpeg, but i am do nothing in these project currently. 
i use ffmpeg command can record video from rtsp currently.    
[logs.txt](https://github.com/kokorin/Jaffree/files/8713497/logs.txt)

**Comment by lye2018** [comment]
i just want to record video  from rtsp, maybe you can give me a choice.

**Comment by lye2018** [comment]
i am sorry. i change the function (Cut and scale media file) 'execute' to 'executeAsync', now i restore, i found these logs.
maybe i need install ffmpeg in my os or do something  about ffmpeg configure in my project
[logs.txt](https://github.com/kokorin/Jaffree/files/8713898/logs.txt)

**Comment by lye2018** [comment]
ok, thanks
