### ISSUE TITLE
How do you get the error message returned by FFmpeg?

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#305]
Hi,

Is it possible to get the specific error message returned by FFmpeg (specfically I'm interested in whether "Conversion failed!" was the reason for failure)?

Back in the days FFmpegResultReader did some stateful magic in its read() method which threw a RuntimeException prefixed by `ffmpeg exited with message:` which did the trick, but this logic is gone in the latest version which we are migrating to.

Any help would be appreciated.

Thanks!

**Comment by kokorin** [comment]
@jonfryd thank you, let me know if you have any issues with the MR

**Comment by jonfryd** [comment]
Hey kokorin, so I've just opened PR #306 which does what you suggested to me.
