### ISSUE TITLE
FFMpeg process takes 10sec to start the stream

### ISSUE THREAD

**Issue by SheikhZayed** [kokorin/Jaffree#335]
**Describe the issue**
Once a request for stream is received, it takes 10s for the process to create index file, any possible way to speed up this lag ?

**Comment by kokorin** [comment]
Discussions are more suitable for such questions.
What is ffmpeg command you use? Have you checked ffmpeg CLI without Jaffree?

**Comment by SheikhZayed** [comment]
i use the following command 

`ffmpeg -loglevel level+info -n -rtsp_transport tcp -i rtsp://admin:admin.com@1234@192.168.20.111/video1 -f hls -vsync 0 -copyts -vcodec copy -b:a 96k -acodec copy -movflags frag_keyframe+empty_moov -hls_flags delete_segments+append_list -hls_time 5 -hls_list_size 5 /Users/desktop/index.m3u8`

could you pleease verify

**Comment by SheikhZayed** [comment]
Thanks @kokorin
