### ISSUE TITLE
DemuxerInput.java   not found

### ISSUE THREAD

**Issue by yiyezhangmu** [kokorin/Jaffree#353]
I　try  to concat same format video  ，but can not find  DemuxerInput.java in new version

String video1Path = "path/to/video1.mp4";
        String video2Path = "path/to/video2.mp4";
        String outputPath = "path/to/output.mp4";

        FFmpeg.atPath()
                .addInput(
                        ConcatDemuxerInput.addSubInput(
                                UrlInput.fromPath(video1Path),
                                UrlInput.fromPath(video2Path)
                        )
                )
                .addArguments("-c", "copy") // 使用流复制
                .setOutput(
                        UrlOutput.toPath(outputPath)
                )
                .execute();

**Comment by kokorin** [comment]
There have never been ConcatDemuxerInput in Jaffree

вс, 18 июн. 2023 г., 06:16 jeffreyyang ***@***.***>:
