### ISSUE TITLE
issues with ffprobe showFormat and multiline tags

### ISSUE THREAD

**Issue by st-h** [kokorin/Jaffree#41]
I came across a file which seems to have tags that contain values that span multiple lines. This seems to cause the DataParser to error:

```
Caused by: java.lang.RuntimeException: key=value was expected but got: 
	at com.github.kokorin.jaffree.ffprobe.data.DataParser.parseLine(DataParser.java:54)
	at com.github.kokorin.jaffree.ffprobe.data.DataParser.parse(DataParser.java:151)
	at com.github.kokorin.jaffree.ffprobe.FFprobeResultReader.read(FFprobeResultReader.java:40)
	at com.github.kokorin.jaffree.ffprobe.FFprobeResultReader.read(FFprobeResultReader.java:32)
	at com.github.kokorin.jaffree.process.ProcessHandler$3.run(ProcessHandler.java:186)
	at com.github.kokorin.jaffree.process.Executor$1.run(Executor.java:49)
```
with showFormat enabled:
```
ffmpeg.setShowFormat(true)
```
running ffprobe with options `ffprobe -loglevel 16 -show_format -show_private_data` shows this output (long text shortened with `...`):
```
[FORMAT]
filename=/tmp/cvma7ou0kk5infmok4403378daciqkia/cvma7ou0kk5infmok4403378daciqkia.mp3
nb_streams=2
nb_programs=0
format_name=mp3
format_long_name=MP2/3 (MPEG audio layer 2/3)
start_time=0.011995
duration=122.044082
size=2029181
bit_rate=133012
probe_score=51
TAG:comment=The most popular...way.

Samples...provide.

Then,...format
TAG:encoder=Lavf56.40.101
[/FORMAT]
```

I was thinking about modifying the dataParser so that it if it does not find a new tag, it will add the content to the previous value. However, that probably will blow up as easy as the multiline value containing a `=`. Maybe a better approach would be to only parse values we know are relevant for ffprobes result and ignore everything else? Or we just ignore multiline tags, by simply returning instead of throwing an error? what do you think?

The file is available here https://www.dropbox.com/s/wsczg7umwfx0isc/multiline.mp3?dl=0

I was also having some issues running the tests locally, mostly because I was unable to find the input files required for testing. Are they available for download somewhere?

**Comment by kokorin** [comment]
Run maven build first. In pom.xml you can find plugin which downloads files.

**Comment by st-h** [comment]
@kokorin ah sorry, I was executing the tests via IDE, which bypassed the maven stage.
I simply subclassed FFprobe and removed the thrown exception in the DataParser within my code, which works fine for now (truncating multiline tags, however I am only interested in the format anyways). Do you have any preference how to solve this issue?

**Comment by kokorin** [comment]
@st-h I haven't found anywhere description of ffprobe default output format. So it seems to be a bug in parser. 
I would be pleased to accept pull request.

**Comment by st-h** [comment]
I think the problem is, that it is kind of impossible to determine from the command line output if we are dealing with a new line due to a multiline tag, or if FFmpeg inserted a newline because we are dealing with a new tag. This makes it quite difficult to reliably support multiline output. 
I think as a short term solution the easiest thing to do would be to just remove the exception from the parser and let it continue and ignore the line it can not deal with. However, I think this mostly comes down to what we expect from Jaffree. If we want the most accurate output, we probably should change the parser to look explicitly for the values we require for the probe result - and try to do our best to add additional newlines to the previous tag. However, I think that will be quite a refactoring and probably will only increase accuracy in very few edge cases. So it might be better to just remove the exception for now and see if that is good enough, making the parser more resilient.

**Comment by kokorin** [comment]
@st-h I have released new 0.8.1 version, which introduces FormatParser. You can implement your own, if you need and use it with FFprobe#setParser().
There are two implementations: FlatFormatParser (new one, used by default) and DefaultFormatParser (called so because it parses default ffprobe output format).

**Comment by st-h** [comment]
@kokorin thanks a lot. `0.8.1` worked perfectly so far right out of the box. `print_format` seems like a great option to fix those things. Did not notice that so far. awesome 👍 In case there still should be issues with complex stuff, we could also probably switch to json format in the future, which might make parsing easier.

**Comment by kokorin** [comment]
@st-h thanks for letting me know!
Glad it works for you
