### ISSUE TITLE
Expose destroy/destroyForcibly in ffmpeg instance

### ISSUE THREAD

**Issue by dyorgio** [kokorin/Jaffree#49]
Save instance of main created Process as FFMpeg class field, than provide a way to developer call destroy/destroyForcibily.

Related with: #20

**Comment by kokorin** [comment]
It's not possible to stop ffmpeg gracefully with Jaffree. But to stop it forcefully one can use 3 ways:

1. Throw an exception in `ProgressHandler `(as stated in #20)
2. Start ffmpeg with `com.github.kokorin.jaffree.ffmpeg.FFmpeg#execute()` and interrupt thread running Jaffre
3. Start ffmpeg with `com.github.kokorin.jaffree.ffmpeg.FFmpeg#executeAsync()` which returns an instance of `Future<FFmpegResult>`. Stop ffmpeg with `future.cancel(true)`

**Comment by dyorgio** [comment]
Tks for replying @kokorin, sadly it only interrupt java threads.
I’m talking about kill external ffmpeg process ( free up cpu and other resources).
In my cenario (stream) will run for a indefinitely time, so I really need kill it, a PID (or a list of) can help too...

**Comment by kokorin** [comment]
@dyorgio check `com.github.kokorin.jaffree.process.ProcessHandler#execute`, it does stop ffmpeg. Thread interruption is what `future.cancel(true)` does: `true` means "may interrupt if running".
I'm pretty sure all above mentioned methods work. 
If it's not true please provide sample project which demonstrates that.

**Comment by dyorgio** [comment]
I see... in line 90, a destroy on finally :).
