### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by eos1d3** [kokorin/Jaffree#5]
Is it possible to add Javadoc? Some methods are difficult to understand what they do.
Thanks.

PS: This is nice FFMPEG wrapper.

**Comment by kokorin** [comment]
Could you give some examples of methods, lacking JavaDocs? I tried to make Jaffree as simple as possible. 

Anyway, I would appreciate any contribution to the project.

**Comment by eos1d3** [comment]
Sorry it was because my Maven in Eclipse is not refreshed so that JavaDoc is not shown.
Everything is working fine now.

Anyway, thanks!
