### ISSUE TITLE
32-bit integer overflow when calling Stream.getBitRate

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#54]
Hi @kokorin,

I'm getting a NumberFormatException when calling getBitRate() on a probed Stream (for very high bitrate videos like e.g. UHD 8K).

For example:

```Failed to parse integer number: 2498657137```

An upgrade from Integer to Long would fix this it seems.

Cheers,
-Jon

**Comment by kokorin** [comment]
Hi @jonfryd thanks for reporting. 
Do you have other suspects? I mean suspicious variables or places where to put extra attention?

Best regards,
Denis

**Comment by kokorin** [comment]
BTW, you can use a workaround:
```
FFprobeResult probe = ...
Stream stream = probe.getStreams().get(0);
Long bitrate = stream.getSection().getLong("bit_rate");
```

**Comment by jonfryd** [comment]
Cool! Thanks for your workaround, @kokorin.

Regarding suspicious variables, the only other one that I suspect might overflow is the max bitrate, i.e. getMaxBitRate(), but I didn't perform a deep review.

Anyway, thanks for your great work as always. Much appreciated. 👍

**Comment by kokorin** [comment]
Hi @jonfryd ,
Version 0.9.2 has been released. contains fixes for bitrate-related properties.
Also now it's possible to supply InputStream and SeekableByteChannel to FFprobe.

Best regards,
Denis Kokorin.

**Comment by jonfryd** [comment]
Awesome! Thanks, @kokorin.
