### ISSUE TITLE
[Feature-Request] - RTMP / RTMPS?

### ISSUE THREAD

**Issue by StevenPG** [kokorin/Jaffree#55]
I just recently completed a project with ffmpeg-cli-wrapper and RTMP with Facebook live. There's no good Java FFMPEG library out there today that performs RTMP/RTMPS output, which ffmpeg is capable of doing. Ex. https://hackernoon.com/build-live-video-streaming-server-use-ffmpeg-nginx-rtmp-module-nodejs-82e1bb58949e (not my page, just random example)

I was going to fork ffmpeg-cli-wrapper and add it, before I came across Jaffree. I wouldn't mind helping do the addition, is this something you might consider? It's a little confusing to me that there are basically NO RTMP libraries for Java, so no easy way to stream out.

**Comment by kokorin** [comment]
Hello @StevenPG 

Actually I always help people with their questions about Jaffree. And of course I would like to help you, but it seems I don't fully understand what you want. Could you describe with a bit more details?

Also Jaffree is essentially command-like wrapper, it means that with it you can't do anything that is not possible with only ffmpeg and /or its libraries. 

Best Regards,
Denis Kokorin.

**Comment by StevenPG** [comment]
Sure, so with ffmpeg you can do something like this:

`ffmpeg -re -i /var/Videos/test.mp4 -c copy -f flv rtmp://localhost/myapp/mystream
`

This will stream video from test.mp4 to an RTMP server at localhost/myapp/mystream.

Being able to do this through Java would allow someone to use Java to build an application that might hit the Facebook Live or Youtube Live APIS: https://developers.facebook.com/docs/live-video-api/guides/streaming

After authenticating with FB/YT, you get the following response:

`{
  "id": "1953020644813104",
  "stream_url": "rtmp://rtmp-api.facebook...",
  "secure_stream_url":"rtmps://rtmp-api.facebook..."
}`

So you can run `ffmpeg -re -i /var/Videos/myvideo.mp4 -c copy -f flv rtmp://rtmp-api.facebook...`

Currently, it looks like there's no Java library today that lets you do this, but it is fully supported within ffmpeg. Let me know if this is enough info!

**Comment by kokorin** [comment]
Hello @StevenPG!

What is possible to do with command line is also possible to do with a help of Jaffree.
Try something like the following:

```java
FFmpegResult result = FFmpeg.atPath(ffmpegBin)
        .addInput(
            UrlInput
                .fromUrl(" /var/Videos/myvideo.mp4")
                .addArgument("-re")
         )
        .addOutput(
            UrlOutput
                .toUrl("rtmp://rtmp-api.facebook...")
                .setFormat("flv")
                .copyAllCodecs()
         )
        .setOverwriteOutput(true)
        .execute();
```

Honestly I'm not sure if it's possible with ffmpeg to stream FLV from MP4 source. 
I can recommend to convert MP4 to FLV first and then to stream resulting FLV with the same parameters. 

I do stream FLV to RTMP servers for testing, so I'm 100% sure it's possible.

Best Regards,
Denis Kokorin.

**Comment by StevenPG** [comment]
Interesting! I will do some digging and see if I can rebuild my previous project with the CLI directly into using Jaffree and see if I can gain the same functionality. It looks like it though!

Thank you for taking the time to provide the sample of the same capabilities!

**Comment by kokorin** [comment]
@StevenPG thank you for letting me know!
Feel free to ask more questions if you need.

Best regards,
Denis Kokorin
