### ISSUE TITLE
MP4 conversion to outputStream is not working

### ISSUE THREAD

**Issue by berserkore** [kokorin/Jaffree#56]
it fails to convert an AVI file to MP4 stream:
`FFmpeg.atPath(BIN)
                                .addInput(UrlInput.fromPath(VIDEO_AVI))
                                .addOutput(PipeOutput.pumpTo(out).setFormat("mp4"))
                                .setOverwriteOutput(true)
                                .execute()`

But ending up with 

**java.lang.RuntimeException: Failed to execute, exception appeared in one of helper threads
...
Caused by: java.lang.RuntimeException: Exception during execution
...
Caused by: java.lang.RuntimeException: ffmpeg exited with message: Conversion failed!**

Notice that the same approach works when converting an avi file to FLV stream:
`FFmpeg.atPath(BIN)
                                .addInput(UrlInput.fromPath(VIDEO_AVI))
                                .addOutput(PipeOutput.pumpTo(out).setFormat("flv"))
                                .setOverwriteOutput(true)
                                .execute()`

**Comment by kokorin** [comment]
Hi @berserkore 
Thank you for your attention to this library!

What you have faced is a general restriction of non-seekable output. FFMPEG just can't finalize AVI (as well as MP4 and other formats) without seeking. 

So you have 2 options: either to use SeekableByteChannel (chek ChannelInput) or to write output to a file on local file system and later to upload it via InputStream wherever you want.

Best regards,
Denis Kokorin.

**Comment by berserkore** [comment]
Thanks for your guidance @kokorin,
Do you have any sample code where we can use both SeekableByteChannel and outputStream for a mp4 conversion?

**Comment by kokorin** [comment]
Hi @berserkore ,
Could you give me more details about what you want to achieve? Why do you need SeekableByteChannel & OutputStream at the same time?

Examples how to use ChannelOutput you can find [here](/kokorin/Jaffree#supplying-and-consuming-data-with-seekablebytechannel)

**Comment by berserkore** [comment]
Hi @kokorin 

This is because I need a conversion on the fly to MP4. Please see the following.

                   `
....
 override fun write(out: OutputStream) {
FFmpeg.atPath(BIN)
 .addInput(UrlInput.fromPath(VIDEO_MP4))
.addOutput( ChannelOutput.toChannel("channel.mp4", channel)) //<-- Just write to a file, I need a way to redirect the byte to the out variable
// .addOutput(PipeOutput.pumpTo(out).setFormat("mp4")) <-- not working but does mp4 conversion the fly
 .execute()
}
`

Do you know any other way to perform the conversion on the fly using both ChannelOutput and OutputStream?

**Comment by kokorin** [comment]
Hi @berserkore ,

FLV was created for video streaming so, to mux FLV you need no seeking. MP4 wasn't created for streaming. To mux it you do need seeking. 

In code comments you wrote: "Just write to a file, I need a way to redirect the byte to the out variable". That's not possible. Because ffmpeg seeks into MP4 file while writing it. You can't stream seeks.

That's not an option to use both ChannelOutput and OutputStream. Actually I don't understand why you ask about them both.

But if you really need MP4 and OutputStream, well, you can produce **fragmented** MP4, which doesn't require seeking. But this is **not standard** MP4 and many players may have **problems** with it.
So to produce it you need to add `-movflags empty_moov`

**Comment by kokorin** [comment]
Also you wrote
> not working but does mp4 conversion the fly 
That's not actually true. FFMPEG doesn't even start conversion because it detects that output is a TCP output. which is not seekable.

**Comment by berserkore** [comment]
Ok, thanks for your thoughts.
