### ISSUE TITLE
[QUESTION] Does the end user have to install FFMPEG too?

### ISSUE THREAD

**Issue by MatijaBrown** [kokorin/Jaffree#58]
This is a dumb question, I know, but I have not worked with parser a lot yet, and I'd like to know if this includes FFMPEG into the jar file, when I export it as a jar. I'm sorry for asking dumb questions but I don't want the end users of my program to have to install FFMPEG.

**Comment by kokorin** [comment]
@MatijaBrown Of course ffmpeg and ffprobe are not included into jar-file. If they were it would significantly increase jar size by 100 times.

So you have to install ffmpeg and ffprobe and either pass installation folder to Jaffree, or add ffmpeg and ffprobe to PATH env variable.

**Comment by MatijaBrown** [comment]
Thanks for the reply. I thought this was going to be the case. Although I do consider this to be slightly impractical as every user would have to install FFMPEG. But thanks for the reply.
