### ISSUE TITLE
[Question] how to make filter output like: FilterName='...'

### ISSUE THREAD

**Issue by timzaak** [kokorin/Jaffree#59]
```scala
// this is my code:
FFmpeg.atPath(Paths.get("/usr/local/bin")).addInput(UrlInput.fromPath(video)).setComplexFilter(FilterGraph.of(
    FilterChain.of(
      Filter.withName("drawtext")
        .addArgument("text", "String1")
        .addArgument("expansion", "normal")
        .addArgument("y", "h-line_h-10")
        .addArgumentEscaped("x", """(mod(5*n\,w+tw)-tw)""")
        .addArgument("fontcolor", "white")
        .addArgument("fontsize", "40")
        .addArgument("shadowx", "2")
        .addArgument("shadowy", "2")
    ))).addOutput(UrlOutput.toPath(videoOutPut)).execute()
// error output
// ffmpeg -i test.mp4 -n -filter_complex drawtext=text=String1:expansion=normal:y=h-line_h-10:x=(mod(5*n\,w+tw)-tw):fontcolor=white:fontsize=40:shadowx=2:shadowy=2 out/test.mp4

```
how could I get  the correct out: `ffmpeg -i test.mp4 -n -filter_complex drawtext='text=String1:expansion=normal:y=h-line_h-10:x=(mod(5*n\,w+tw)-tw):fontcolor=white:fontsize=40:shadowx=2:shadowy=2 out/test.mp4'`

the following code can work, but I don't think it's the best way:
```scala
Filter.withName("drawtext").addArgumentEscaped("""'text=String1:expansion=normal:...'""")
```

**Comment by kokorin** [comment]
Your question is similar to #53 
In short in Java you pass arguments to a Process without need to escape spaces. Jaffree prints arguments, not command line.
In your command line I see that `out/test.mp4` is a part of complex filter.

Filter, FilterGraph and FilterChain are only for more readable code. You can pass whole filter chain as arguments directly:
FFmpeg.atPath().addArgument("""drawtext='text=String1:expansion=normal:...'""")

It's hard to say anything more without full logs or sample project.

**Comment by timzaak** [comment]
thanks
