### ISSUE TITLE
How to get video duration of a file using this library

### ISSUE THREAD

**Issue by rameshvoltella** [kokorin/Jaffree#62]
This not an issue can you tell me how can we get the video information mainly video duration using this library

**Comment by kokorin** [comment]
Don't have this examples now, but you can find code samples in tests

**Comment by rameshvoltella** [comment]
@kokorin i got it from [here]("https://github.com/kokorin/Jaffree/blob/master/src/test/java/com/github/kokorin/jaffree/ffprobe/FFprobeTest.java), working fine for mp4 videos but when i try to get info for mkv its return null can you tell me why?

**Comment by rameshvoltella** [comment]
@kokorin also how we will know the task is finished or not

**Comment by rameshvoltella** [comment]
@kokorin how to updat ui base on the progress it tried but my ui not updating

**Comment by rameshvoltella** [comment]
@kokorin any help?

**Comment by kokorin** [comment]
Check ffprobe output. If it doesn't contain duration it's not a bug in Jaffree.
In that case you can use ffmpeg to detect real duration with encoding to `/dev/null`. Check NullOutput.

**Comment by kokorin** [comment]
@rameshvoltella I have updated README and added examples how to get exact duration of video file.
Check full [example](/kokorin/Jaffree/blob/master/src/test/java/examples/ffprobe/ShowStreams.java)
