### ISSUE TITLE
Add duration detect examples

### ISSUE THREAD

**Issue by kokorin** [kokorin/Jaffree#63]

**Comment by rameshvoltella** [comment]
@kokorin super its a great addon ,just one more help can you tell be how to identify when a process got finisheh, because onprogress dont give a excate result.is there any other way to find the process finished or not?

**Comment by kokorin** [comment]
If you use `FFmpeg#execute()` an encoding is finished when `FFmpeg#execute()` exits.

Otherwise if you use `FFmpeg#executeAsync()`  you should check execution status on `Future<FFmpegResult>` which this methods returns.
