### ISSUE TITLE
FFmpeg -skip_frame option

### ISSUE THREAD

**Issue by zivkovic** [kokorin/Jaffree#68]
There is no option to include '-skip_frame nokey' argument in the command.

The '-skip_frame' has to be used before '-i file.mp4' argument for it to work, this is also the reason 'addArgument' method cannot be used.

The cheapfix I use now, is to extend FFmpeg class and override buildArguments method to include this argument. It would be great if you could provide an easier built in way to set this.

If you wish I can provide you with the pull request to include this functionality.

**Comment by kokorin** [comment]
> There is no option to include '-skip_frame nokey' argument in the command.

You can use `UrlInput.addArguments()`. It will add arguments before **-i filemame**

**Comment by zivkovic** [comment]
I actually have not noticed that. As expected it does exactly what I want.

Thanks!
