### ISSUE TITLE
Merge multiple videos into one

### ISSUE THREAD

**Issue by kaszperro** [kokorin/Jaffree#69]
Hi,

How to merge multiple videos into one?
I mean using this ffmpeg function https://ffmpeg.org/ffmpeg-filters.html#concat .
This python library makes it really simple: https://github.com/kkroening/ffmpeg-python
just calling .concat function.
Is something similar here possible, without writing tons of custom ffmpeg arugments?

**Comment by kaszperro** [comment]
For now, to concatenate list of videos I have to write:

        FFmpeg ffmpeg = FFmpeg.atPath();

        for (SubVideoInfo videoInfo : videosToConcat) {
            ffmpeg.addInput(
                    UrlInput.fromPath(videoInfo.getVideoPath())
                            .setPosition((long) (videoInfo.getStartTime() * 1000))
                            .setDuration((long) (videoInfo.getDuration() * 1000)));
        }


        StringBuilder concatBuilder = new StringBuilder("\"");
        for (int i = 0; i < videosToConcat.size(); ++i) {
            concatBuilder
                    .append("[")
                    .append(i)
                    .append(":v:0]");
            concatBuilder
                    .append("[")
                    .append(i)
                    .append(":a:0]");
        }
        concatBuilder.append("concat=n=")
                .append(videosToConcat.size())
                .append(":v=1:a=1[outv][outa]")
                .append("\"");

        ffmpeg.addArguments("-filter_complex", concatBuilder.toString());
        ffmpeg.addArguments("-map", "\"[outv]\"");
        ffmpeg.addArguments("-map", "\"[outa]\"");

        ffmpeg.addOutput(UrlOutput.toPath(savePath));
        ffmpeg.execute();

Is there easier, more compact way?

**Comment by kokorin** [comment]
@kaszperro Probably in your case you don't need complex filter at all - ffmeg can concat multiple input files.
Regarding your question: Jaffree doesn't provide extra functionality except command line. Of course such project which leverages Jaffree would be helpful.

**Comment by kaszperro** [comment]
Thanks for answer, but calling only `.addInput()` didn't work well. I'll stick with what I wrote.
