### ISSUE TITLE
Iphone videos

### ISSUE THREAD

**Issue by Emmenemoi** [kokorin/Jaffree#7]
Some iPhone video are rotated 90°. FFProbe output is as follow:
```
<stream>
<side_data_list>
                <side_data side_data_type="Display Matrix" displaymatrix="
00000000:            0       65536           0
00000001:       -65536           0           0
00000002:     70778880           0  1073741824
" rotation="-90"/>
</side_data_list>
</stream>
```
Jaffree can't get this rotation info due to current Jaffree XML schema definition.

FFMpeg is using this attribute when transcoding and inverts height and width automatically. If we force scale filter, it is not auto inverting height and width (as expected) but still rotates the frames. We should know this rotation parameter to specify the correct scale dimensions.

**Comment by kokorin** [comment]
Thanks for your interest to this project.
If it's urgent you can just add corresponding attribute to PacketSideData class and build.

I got XSD from ffmpeg site or project (don't remember exactly), and for some reason it [doesn't contain](https://github.com/FFmpeg/FFmpeg/blob/master/doc/ffprobe.xsd) such attributes.

I will take a closer look  on weekend.

**Comment by kokorin** [comment]
Thanks for letting me know

**Comment by kokorin** [comment]
Have you seen or created corresponding ticket for ffmpeg team?
Could you provide me with a link to iPhone video for which this problem appears?

**Comment by kokorin** [comment]
Created [ticket ](https://trac.ffmpeg.org/ticket/7139)for ffmpeg team.
