### ISSUE TITLE
question implement -fflags nobuffer

### ISSUE THREAD

**Issue by otmanel31** [kokorin/Jaffree#70]
Hi, i'm trying to implement this command and more precisely -fflags notbuffer arguments  in order to minimize delay and avoid latency:
=> ffplay -fflags nobuffer -rtsp_transport tcp rtsp://<host>:<port>
This command is explained [here](https://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg). 
Is it possible to add it using  FFmpeg#addArguments method ?

**Comment by kokorin** [comment]
Hello,
Actually Jaffree is command line wrapper so it doesn't work with ffplay.
However, you can extract video and audio frames as images and samples with
it.
Could you describe in more details what you want to do with ffplay, how you
would control ffplay window from Java and provide command lines?

пн, 24 февр. 2020 г., 20:04 otmanel31 <notifications@github.com>:

**Comment by otmanel31** [comment]
cuurently, i'm executing ffmpeg to get video over rtsp. But i face few latency (2 seconds or more).
As describe in this [link](https://trac.ffmpeg.org/wiki/StreamingGuide#Latency) and above link, -fflags or probsize args should help to reduce latency. My question is could this args reduce latency ? is there a buffering when using ffmpeg ?

**Comment by kokorin** [comment]
Sorry for long reply,
Actually I can't answer the question. It's possible to add this argument with Jaffree. Jaffree itself doesn't buffer anything (unless you work with frames from Java).
So I can recommend to experiment to get an answer.

**Comment by otmanel31** [comment]
no problem,
Ok so i'll try it. 
So, if i'd like to add new args, i should use FFmpeg#addArguments method ?

**Comment by otmanel31** [comment]
I close this issue as it's only a question
