### ISSUE TITLE
Sometimes ffprobe can't show exact duration?

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#72]
Hi @kokorin,

Hope you are doing well and thanks again for doing Jaffree.

I have been wondering for a while about this comment in one of your examples of how to use Jaffree:

`//Sometimes ffprobe can't show exact duration, use ffmpeg trancoding to NULL output to get it`

What exactly do you mean here? 

1. The duration value might not be available (`N/A`) in stream metadata? I have noticed this is the case for Matroska containers (.mkv), in which case the duration can instead be found instead as part of the parent format metadata.
2. The value might be inaccurate?
3. Something else?

I would be happy if you could clear this up.

Cheers,
-Jon

**Comment by kokorin** [comment]
Hi @jonfryd ,
I meant that for some formats there may be no duration metadata (probably FLV live stream recording). Also the value provided by ffprobe may be inacurate. Check [FFprobeTips](https://trac.ffmpeg.org/wiki/FFprobeTips):
`Note: Not all formats, such as Matroska and WebM, store duration at the stream level resulting in duration=N/A. Refer to Format (container) duration instead. `

**Comment by jonfryd** [comment]
OK, thanks. That makes sense.

What kind of inaccuracy are we talking about? Milliseconds? More?

**Comment by kokorin** [comment]
I saw difference in several seconds, may be files were corrupted.

**Comment by jonfryd** [comment]
OK, thanks. It's good to keep this potential issue in mind with blindly relying on metadata in the context of corrupted files.
