### ISSUE TITLE
Not able to consume from my custom tcp server

### ISSUE THREAD

**Issue by otmanel31** [kokorin/Jaffree#73]
Hi, i'm using below ffmpeg command in order to redirect stream via tcp url.
When i began, i used this command:

> FFmpeg.atPath(Paths.get(this.manager.getFfmpegPath())).addInput(UrlInput.fromUrl(rtspURL))
					.addArguments("-c:v", "copy")
					.addArguments("-c:a", "aac")
					.addArguments("-fflags", "nobuffer") 
					.setLogLevel(LogLevel.DEBUG)
					 .addOutput(PipeOutput.pumpTo(outputStream).setFormat("mpegts"))
                                        .setOverwriteOutput(true)
					.executeAsync();
This command work but i received in my outputstream 65kB that is big for my usecase. and when i tried to bufferize and cut inciming byte[], the process is brutally stopped.
So i decided to set my own tcp server and change ffmpeg command like this but nothing happen:

>  FFmpeg.atPath(Paths.get(this.manager.getFfmpegPath())).addInput(UrlInput.fromUrl(rtspURL))
					.addArguments("-c:v", "copy")
					.addArguments("-c:a", "aac")
					.addArguments("-fflags", "nobuffer") 
					.setLogLevel(LogLevel.DEBUG)
					 .addOutput(UrlOutput.toUrl(tcpUrl).setFormat("mpegts"))
                                        .setOverwriteOutput(true)
					.executeAsync();
an idea of ​​what's wrong? or may be this is not the good way ?

**Comment by kokorin** [comment]
Hi @otmanel31 
Please, provide ffmpeg & Jaffree debug logs.

**Comment by otmanel31** [comment]
Hi, thanks for quick reply. Below piece of logs of related issue. But only one problem, i'm not able to provide ffmpeg log which are the most important .... because of  a SLF4J binding issue may be. I will check it tomorow. I don't know why ffmpeg debub log doesn't work correctly. I remember i used it few times ago, and that worked. 

> 15:48:36.835 [Thread-2] INFO  com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> FFMPEG version -> ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
15:48:36.845 [pool-6-thread-1] INFO  com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> starting tcpserver in sub task
SLF4J: Class path contains multiple SLF4J bindings.
15:48:36.845 [pool-6-thread-1] INFO  com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> tcp server waiting for connection
SLF4J: Found binding in [jar:file:/C:/Users/someUser/Desktop/gero-hik-r3/gero/nx-edge-main.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/someUser/Desktop/gero-hik-r3/gero/plugins/sub-service-1.16.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
15:48:36.855 [Thread-2] INFO  com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> Video stream started for device camera_hd
15:48:36.855 [ForkJoinPool.commonPool-worker-19] DEBUG com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> receiving response from stream_video
5 [FFmpeg-async-runner] INFO com.github.kokorin.jaffree.process.ProcessHandler - Command constructed:
C:\Users\someUser\Documents\openFaas\ffmpeg -loglevel 48 -i rtsp://admin:**********@192.168.1.17:556/Streaming/Channels/101?transportmode=unicast -y -c:v copy -c:a aac -fflags nobuffer -f mpegts tcp://127.0.0.1:55847
5 [FFmpeg-async-runner] INFO com.github.kokorin.jaffree.process.ProcessHandler - Starting process: C:\Users\someUser\Documents\openFaas\ffmpeg
35 [FFmpeg-async-runner] INFO com.github.kokorin.jaffree.process.ProcessHandler - Waiting for process to finish
15:48:38.399 [pool-3-thread-1] DEBUG com.capsulecorp.gero.edge.grpc.GrpcManager - set logs response -> result: "OK"
15:48:39.244 [pool-6-thread-1] INFO  com.capsulecorp.gero.edge.ServiceImpl - serviceUid -> 11620000-d417-4016-b01f-28f064cd4e95 | message -> connection to tcp server detected.
2423 [FFmpeg-async-runner] INFO com.github.kokorin.jaffree.process.ProcessHandler - Process has finished with status: 1

**Comment by otmanel31** [comment]
The very strange behaviour is that some moment, the ffmpeg process start and finish with status 1, some moment nothing happen, some moment i got 2 or 3 packet and the process shutdown again with status1.

So, i decided to create an other java program in order to test it again, with ffmpeg log ( and without  SLF4J binding issue), and waaw ...  everything is ok. And the code is the same for getting video but without other logic as sending then every packet to  a broker (mqtt for example).

**Comment by kokorin** [comment]
How do you extract packets? It's highly probable ffmpeg can't write mpegts
to TCP transport.
It's also possible to put some breakpoints to check what's wrong with slf4j
binding.

чт, 7 мая 2020 г., 20:32 otmanel31 <notifications@github.com>:

**Comment by otmanel31** [comment]
i'm giving you an examplle below from a java program that reproduce what i did in my app.
This code work successfully but when i implement it in my app, some moments i have a " process shutdown again with status1" message.

I'm trying to fix SLF4j issue It's difficult to put a breakpoints as my app is a plugin loaded by an main app.
`public class App 
{
	final static Logger logger = Logger.getLogger(App.class);
	private static Future<FFmpegResult> result;
	private static String tcpUrl = null;
	private static ServerSocket serverSocket = null;
	
	public static void main( String[] args )
	{
		logger.info("Hello tcpserver ... !");
		ExecutorService exec = Executors.newFixedThreadPool(1);
		exec.submit((Runnable) () -> {
			serverSocket = allocateSocket();
			tcpUrl = "tcp://127.0.0.1:" + serverSocket.getLocalPort();
			try {
				// listen for connection
				logger.info("waiting for connection");

				Socket socket = serverSocket.accept();
				logger.info("connection.");

				//read incomoing data
				BufferedInputStream bufStream = new BufferedInputStream(socket.getInputStream());
				int read = 0;
				int nb = 0;
				byte[] buffer = new byte[32800];
				while (read != -1) {
					read = bufStream.read(buffer, 0, 32800);
					//send data over pulsar
					logger.info("Video packet size " + read );
				}

				//close connection
				socket.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		});
		
		// run process
		Process process;
		try {
			String ffmpegCmd = "ffmpeg";
			// for windows only
			ffmpegCmd = Paths.get("C:\\Users\\mrrobot\\Documents\\openFaas", ffmpegCmd).toString();
			logger.info("ffmpeg => " + ffmpegCmd);
			
			process = new ProcessBuilder(ffmpegCmd, "-version").start();
			if (!process.waitFor(1, TimeUnit.SECONDS) || process.exitValue() != 0) {
				throw new IOException("Fail to get ffmpeg version");
			}
			// get version
			String version = new String(process.getInputStream().readAllBytes());
			logger.info("FFMPEG version " + version);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		/*OutputStream outputStream = new TransportStreamOutputStream( 32800, "ok",
				50); */// OLD
		logger.info("start video ...");
		result = FFmpeg.atPath(Paths.get("C:\\Users\\mrrobot\\Documents\\openFaas"))
		.addInput(UrlInput.fromUrl("rtsp://admin:fakepwd@192.168.1.17:558/Channels/101?transportmode=unicast"))
		.addArguments("-c:v", "copy")
		.addArguments("-c:a", "aac")
		.addArguments("-fflags", "nobuffer") 
		//.addArguments("-acodec", "aac")
		.setLogLevel(LogLevel.DEBUG)
		//.addOutput(PipeOutput.pumpTo(outputStream).setFormat("mpegts")).setOverwriteOutput(true)
		.addOutput(UrlOutput.toUrl(tcpUrl)
				.setFormat("mpegts")
		)
		.setOverwriteOutput(true)
		.executeAsync();
		logger.info("execute called");
		
		while (!result.isCancelled()) {
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		/*try {
			int maxBytes = 32768;
			byte[] messageByte = new byte[maxBytes];


			ServerSocket server = new ServerSocket(62665);
			Socket socket = server.accept();
			//socket.setSendBufferSize(16384);
			//socket.setReceiveBufferSize(16384);


			BufferedInputStream bufStream = new BufferedInputStream(socket.getInputStream());
			int noBytesRead = 0;

			// FileOutputStream fis = new FileOutputStream("test.mp4");
			while (noBytesRead != -1 )
			{

				noBytesRead = bufStream.read(messageByte, 0, maxBytes);
				System.out.println(noBytesRead);
				//fis.write(data, 0 noBytesRead);
			}


			//End read

		} catch (IOException e) {
			e.printStackTrace();
		}*/
	}
	public static class TransportStreamOutputStream extends OutputStream {

		// Configuration parameters
		private int min = 0;
		private String deviceId;
		private int numberSegments = 0;

		// Internal attributes
		private byte[] buffer = null;
		private int sum = 0;
		private int nb = 0;
		private boolean closed;
		
		/**
		 * TransportStreamOutputStream constructor
		 * 
		 * @param core       Running core
		 * @param bufferSize
		 */
		public TransportStreamOutputStream( Integer bufferSize, String deviceId,
				Integer numberSegments) {
			// Create the buffer
			this.buffer = new byte[bufferSize * 2];
			// Store configuration parameters
			this.min = bufferSize;
			this.deviceId = deviceId;
			this.numberSegments = numberSegments;
			
			
		}

		@Override
		public void close() throws IOException {
			super.close();
			this.closed = true;
		}

		@Override
		public void write(int b) throws IOException {
		}

		@Override
		public void write(byte b[], int off, int len) throws IOException {
			logger.info("Received => " + len);
			
		}


	}
	private static ServerSocket allocateSocket() {
        try {
            return new ServerSocket(0, 1, InetAddress.getLoopbackAddress());
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }`

**Comment by kokorin** [comment]
Jaffree's part seems to be ok. It's definitely hard to investigate without ffmpeg logs. 
I would concentrate on that.

**Comment by otmanel31** [comment]
i close this issue because i haven't time to investigate on slf4j issue and i'm able to consume correctly on my tcp server packets sent by ffmpeg.

**Comment by kokorin** [comment]
Great,
Thanks for letting me know.

сб, 6 июн. 2020 г., 01:05 otmanel31 <notifications@github.com>:
