### ISSUE TITLE
Small mistake in Mosaic example

### ISSUE THREAD

**Issue by vicnevicne** [kokorin/Jaffree#77]
Testing for audio stream cannot work in this example. 
Indeed this test line: 

`if ("audio".equals(stream.getCodecType())) ...`

compares a String and a StreamType object, which can never be equal. I guess it should read:

`if (StreamType.AUDIO.equals(stream.getCodecType())) ...`

Line is at:
https://github.com/kokorin/Jaffree/blob/master/src/test/java/examples/programmatic/Mosaic.java#L52

Keep on the good work!

**Comment by kokorin** [comment]
Fixed, thanks!
