### ISSUE TITLE
Capturing the desktop

### ISSUE THREAD

**Issue by vicnevicne** [kokorin/Jaffree#78]
I was looking for a way to record a video of the desktop. I tried using java.awt.Robot and feeding ffmpeg through Jaffree but the robot capture is too slow.
I could not find ffmpeg's desktop capture in Jaffree so I guess it's not implemented yet.
So I wrapped up a basic DesktopCaptureInput based on [FFmpeg's desktop capture feature](https://trac.ffmpeg.org/wiki/Capture/Desktop), as well as an example, and would like your opinion on it, so I'm proposing it as a PR.

**Comment by vicnevicne** [comment]
Added an option today to specify the area to capture. This is just an example, and I can only test on Windows,, but I'd be glad to get feedback.

**Comment by kokorin** [comment]
Check 0.9.6 version
