### ISSUE TITLE
ffmpeg hardware acceleration

### ISSUE THREAD

**Issue by sjaiswal25** [kokorin/Jaffree#8]
Is there a way to use hardware acceleration in your code?

Regards

**Comment by kokorin** [comment]
It supports user defined parameters, so you can do with jaffree everything
you can with ffmpeg.


сб, 7 апр. 2018, 14:37 sjaiswal25 <notifications@github.com>:

**Comment by sjaiswal25** [comment]
could you please suggest a starting point for the same, like integrating intel media sdk with this project.

**Comment by kokorin** [comment]
Check [this](https://trac.ffmpeg.org/wiki/HWAccelIntro) and [that](https://developer.nvidia.com/ffmpeg).

But this discussion is out of the scope of Jaffree. Closing.

**Comment by sjaiswal25** [comment]
Thank you

**Comment by kokorin** [comment]
Yeah, that's an artifact of previous version, will update
