### ISSUE TITLE
Player option or advice ?

### ISSUE THREAD

**Issue by vicnevicne** [kokorin/Jaffree#93]
Hi.
I made good progress integrating screen recording using Jaffree in Ginj. No release yet but the [video branch](https://github.com/Ginj-capture/Ginj/tree/video) is already able to select an area, start and stop a capture.
For now, I'm going to just display a thumbnail of the video but I think in the end users should be able to play the video before they decide to save or share it
What would be, in your view, the best way to embed an mp4 player frame in Java ? Can Jaffree help in that regard ? Or do you think another tool or lib is more suitable ?
Kind regards,
Vicne

**Comment by kokorin** [comment]
Hi, check [goxr3plus/XR3Player](https://github.com/goxr3plus/XR3Player). I found it some time ago.

**Comment by vicnevicne** [comment]
Wow, it looks impressive to say the least ;-)
I see it's JavaFX too. Seems JavaFX is the way to go to support playing mp4 files semi-natively. My app is pure Swing, but I guess I can integrate a JavaFX panel with some glue.
Thanks :-)
Closing as it's not a Jaffree issue.
