### ISSUE TITLE
Chapter information does not provide tags (directly)

### ISSUE THREAD

**Issue by rkurman** [kokorin/Jaffree#98]
I'm really not sure whether this is on purpose, but I cannot get the `title` tag from Chapters.

This is the code I'm using (roughly)

```
FFprobeResult probeResult = ffprobe.setShowChapters(true).setShowStreams(true)
				.setShowFormat(true).setInput(videoFile.getAbsolutePath()).execute();
```
The result is parsed as this:

```
List<Chapter> chapters = probeResult.getChapters();
for (Chapter c : chapters) {
    // Code for reading out start/end/...
    List<Tag> tags = c.getTag();
    if (tags != null) {
        for (Tag tag : tags) {
            // Does not get to this point
        }
    }

    // This works...
    DSection section = c.getSection();
    if (section != null) {
        DTag tagsTag = section.getTag("tags");
        if (tagsTag != null) {
            String title = tagsTag.getString("title");
            if (!StringTools.isEmpty(title)) {
                System.out.println("Title: " + title);
            }
        }
    }
}
```

So, the `getTags()` of the Chapter returns an empty list. However, I am able to get the title by accessing the `DSection`.

Am I missing something here?
Thank you!

**Comment by kokorin** [comment]
Probably it's a bug, could you provide media file sample?

вс, 25 окт. 2020 г., 13:35 Roman Kurmanowytsch <notifications@github.com>:

**Comment by rkurman** [comment]
I sent a link to your email address...

**Comment by rkurman** [comment]
0.9.7 fixes this issue. Thanks for the quick help!
